### ISSUE TITLE
Missing ngcp-rtpengine-dbg_6.2.0.0+0~mr6.2.0.0_amd64.deb

### ISSUE THREAD

**Issue by denyspozniak** [sipwise/rtpengine#459] opened 2018-02-14 13:47 UTC
Hello!
I have built debs from master branch, but **ngcp-rtpengine-dbg_6.2.0.0+0~mr6.2.0.0_amd64.deb** is missing.
I am not sure what this package does, so it is only to let you know.

```
root@ip:/usr/src# ls -al | grep ngcp
Feb 14 13:33 ngcp-rtpengine-6.2.0.0+0~mr6.2.0.0
Feb 14 13:30 ngcp-rtpengine_6.2.0.0+0~mr6.2.0.0_all.deb
Feb 14 13:30 ngcp-rtpengine_6.2.0.0+0~mr6.2.0.0_amd64.changes
Feb 14 13:29 ngcp-rtpengine_6.2.0.0+0~mr6.2.0.0.dsc
Feb 14 13:29 ngcp-rtpengine_6.2.0.0+0~mr6.2.0.0.tar.xz
Feb 14 13:30 ngcp-rtpengine-daemon_6.2.0.0+0~mr6.2.0.0_amd64.deb
Feb 14 13:30 ngcp-rtpengine-iptables_6.2.0.0+0~mr6.2.0.0_amd64.deb
Feb 14 13:30 ngcp-rtpengine-kernel-dkms_6.2.0.0+0~mr6.2.0.0_all.deb
Feb 14 13:30 ngcp-rtpengine-kernel-source_6.2.0.0+0~mr6.2.0.0_all.deb
Feb 14 13:30 ngcp-rtpengine-recording-daemon_6.2.0.0+0~mr6.2.0.0_amd64.deb
Feb 14 13:30 ngcp-rtpengine.tar.bz2
Feb 14 13:30 ngcp-rtpengine-utils_6.2.0.0+0~mr6.2.0.0_all.deb

```

**Comment by guillemj** [comment] 2018-02-16 14:14
That old Ubuntu release then would appear not to support generating debug packages automatically, you might need to install the hack they were using at the time, to generate those, with the pkgbinarymangler package.

**Comment by denyspozniak** [comment] 2018-02-16 14:22
I use Ubuntu Server 16.04.3 LTS.
Probably it is not my case.

**Comment by denyspozniak** [comment] 2018-02-16 15:00
Just checked, last version that gives me dbg:

**ngcp-rtpengine-dbg_5.5.3.1+0~mr5.5.3.1_amd64.deb**

```
640388 Feb 16 16:55 mr5.5.3.zip
67538 Feb 16 16:56 ngcp-rtpengine_5.5.3.1+0~mr5.5.3.1_all.deb
4626 Feb 16 16:56 ngcp-rtpengine_5.5.3.1+0~mr5.5.3.1_amd64.changes
1708 Feb 16 16:56 ngcp-rtpengine_5.5.3.1+0~mr5.5.3.1.dsc
499556 Feb 16 16:56 ngcp-rtpengine_5.5.3.1+0~mr5.5.3.1.tar.xz
167030 Feb 16 16:56 ngcp-rtpengine-daemon_5.5.3.1+0~mr5.5.3.1_amd64.deb
942652 Feb 16 16:56 ngcp-rtpengine-dbg_5.5.3.1+0~mr5.5.3.1_amd64.deb
26860 Feb 16 16:56 ngcp-rtpengine-iptables_5.5.3.1+0~mr5.5.3.1_amd64.deb
46184 Feb 16 16:56 ngcp-rtpengine-kernel-dkms_5.5.3.1+0~mr5.5.3.1_all.deb
69526 Feb 16 16:56 ngcp-rtpengine-kernel-source_5.5.3.1+0~mr5.5.3.1_all.deb
50430 Feb 16 16:56 ngcp-rtpengine-recording-daemon_5.5.3.1+0~mr5.5.3.1_amd64.deb
42396 Feb 16 16:56 ngcp-rtpengine-utils_5.5.3.1+0~mr5.5.3.1_all.deb
4096 Feb 16 16:56 rtpengine-mr5.5.3

```

**Comment by guillemj** [comment] 2018-02-16 21:09
Yes latest versions were switched to use the built-in debug package support from debhelper, if your distribution is too old it will not generate those.

**Comment by denyspozniak** [comment] 2018-02-16 21:14
I installed from xenial-backports:

```
root@red5pro:~# dpkg -l | grep debhelp
ii  debhelper                           10.2.2ubuntu1~ubuntu16.04.1                all          helper programs for debian/rules
ii  dh-autoreconf                       12~ubuntu16.04.1                           all          debhelper add-on to call autoreconf and clean up after the build
ii  dh-strip-nondeterminism             0.015-1                                    all          debhelper add-on to strip non-determinism from files


```

**Comment by denyspozniak** [comment] 2018-02-21 09:12
What's version of debhelper I need to have dbg deb?

**Comment by linuxmaniac** [comment] 2018-02-21 12:35
You can take a look over https://wiki.debian.org/AutomaticDebugPackages
debhelper (>= 9.20160114) or newer

**Comment by taurus-forever** [comment] 2018-02-21 12:52
I have just checked Sipwise build environment, the following debug symbol packages are being built in branch master by debhelper (10.2.5):

ngcp-rtpengine-iptables-dbgsym
ngcp-rtpengine-daemon-dbgsym
ngcp-rtpengine-recording-daemon-dbgsym

I am not sure the root of the issue here, so consider JFYI only.
I would be very nice to find the difference and reason of missing dbgsym packages on your side.

**Comment by denyspozniak** [comment] 2018-02-21 12:57
> You can take a look over https://wiki.debian.org/AutomaticDebugPackages
> debhelper (>= 9.20160114) or newer
> 

```
root@red:~# dpkg -l | grep debhelper
ii  debhelper                           10.2.2ubuntu1~ubuntu16.04.1                all          helper programs for debian/rules
ii  dh-autoreconf                       12~ubuntu16.04.1                           all          debhelper add-on to call autoreconf and clean up after the build
ii  dh-strip-nondeterminism             0.015-1                                    all          debhelper add-on to strip non-determinism from files

```

**Comment by taurus-forever** [comment] 2018-02-21 13:07
```
> root@red:\~# dpkg -l | grep debhelper
> ii  debhelper                           10.2.2ubuntu1\~ubuntu16.04.1                all          helper programs for debian/rules
> ii  dh-autoreconf                       12\~ubuntu16.04.1                           all          debhelper add-on to call autoreconf and clean up after the build
> ii  dh-strip-nondeterminism             0.015-1                                    all 
```

I cannot reproduce the issue on Sipwise side with Debian stretch default versions:
debhelper (10.2.5)
dh-autoreconf (14)
dh-strip-nondeterminism (0.034-1)

**Comment by denyspozniak** [comment] 2018-02-21 13:10
I use Ubuntu Server 16.04.3 LTS.
If I send build log, will it help you to find the source of issue?

**Comment by taurus-forever** [comment] 2018-02-21 13:12
Up to @guillemj here.

**Comment by mika** [comment] 2018-02-21 14:18
In Ubuntu's `debhelper` changelog I found:

```
debhelper (9.20160115ubuntu2) xenial; urgency=medium

  * dh-strip: Adjust reversion of commit f1a803456 to account for the recent
    ENABLE_DDEBS → ENABLE_DBGSYM rename. This actually disables -dbgsym
    generation by dh_strip by default again. (LP: #1535949)
```

This matches what's under "Ubuntu" section at https://wiki.debian.org/AutomaticDebugPackages
This doesn't seem to really match what's document in Ubuntu's dh_strip manpage:

```
       --automatic-dbgsym, --no-automatic-dbgsym
           Control whether dh_strip should be creating debug symbol packages when possible.

           The default is to create debug symbol packages.
```

But in Ubuntu's `dh_strip` implementation I stumbled upon:

```
$dh{ENABLE_DBGSYM} = 0 if not $ENV{'DH_BUILD_DDEBS'};
```

@denyspozniak - can you retry building your packages with `export DH_BUILD_DDEBS=1` and see whether this makes any difference?

**Comment by denyspozniak** [comment] 2018-02-21 20:52
Works!

```
79692 Feb 21 22:49 ngcp-rtpengine_6.2.0.0+0~mr6.2.0.0_all.deb
8262 Feb 21 22:49 ngcp-rtpengine_6.2.0.0+0~mr6.2.0.0_amd64.changes
1670 Feb 21 22:48 ngcp-rtpengine_6.2.0.0+0~mr6.2.0.0.dsc
304404 Feb 21 22:48 ngcp-rtpengine_6.2.0.0+0~mr6.2.0.0.tar.xz
185742 Feb 21 22:49 ngcp-rtpengine-daemon_6.2.0.0+0~mr6.2.0.0_amd64.deb
978486 Feb 21 22:49 ngcp-rtpengine-daemon-dbgsym_6.2.0.0+0~mr6.2.0.0_amd64.deb
28680 Feb 21 22:49 ngcp-rtpengine-iptables_6.2.0.0+0~mr6.2.0.0_amd64.deb
2292 Feb 21 22:49 ngcp-rtpengine-iptables-dbgsym_6.2.0.0+0~mr6.2.0.0_amd64.deb
48230 Feb 21 22:49 ngcp-rtpengine-kernel-dkms_6.2.0.0+0~mr6.2.0.0_all.deb
72888 Feb 21 22:49 ngcp-rtpengine-kernel-source_6.2.0.0+0~mr6.2.0.0_all.deb
57594 Feb 21 22:49 ngcp-rtpengine-recording-daemon_6.2.0.0+0~mr6.2.0.0_amd64.deb
178204 Feb 21 22:49 ngcp-rtpengine-recording-daemon-dbgsym_6.2.0.0+0~mr6.2.0.0_amd64.deb
45008 Feb 21 22:49 ngcp-rtpengine-utils_6.2.0.0+0~mr6.2.0.0_all.deb

```

**Comment by mika** [comment] 2018-02-21 23:06
@denyspozniak ok great :)

@guillemj - should we automatically set DH_BUILD_DDEBS if we detect Ubuntu, like:

```
ifeq ($(shell dpkg-vendor --derives-from Ubuntu && echo yes),yes)
    DH_BUILD_DDEBS=1
fi
```

or what's your take on this?

**Comment by guillemj** [comment] 2018-02-22 23:06
The debhelper maintainer refactored some code recently so that the delta with Ubuntu could be reduced. The debug symbol creation was one such aspect. The documentation mismatch is probably just a bug, Might need reporting.

Regarding Ubuntu, I don't think it makes sense to workaround their default in all packages, because the same would happen if you want yo rebuild one of the "official" packages. So perhaps they should also get a bug report, so that they switch the defafult around. Leave generating it automatically by default, so that users get a sane behavior, and they force it to off on their build daemons so that they can control their own custom creation method or whatever.

**Comment by mika** [comment] 2018-02-23 13:44
Thanks for the feedback, @guillemj.

I've just reported this as https://bugs.launchpad.net/ubuntu/+source/debhelper/+bug/1751278 towards Ubuntu and I think we can close this issue, as it's a bug in Ubuntu and there's at least a known workaround available.

**Closed by mika** 2018-02-23 13:44 UTC
