### ISSUE TITLE
RTCP Statistics questionable

### ISSUE THREAD

**Issue by qmex-mp** [sipwise/rtpengine#185] opened 2015-11-17 10:48 UTC
We use kamailio and rtpengine as webrtc Proxy in front of Asterisk (including WebRTC/SRTP to SIP/RTP).

My plan is to implement something like Quality Logging. My actual approach is to pipe the RTCP Logs to a syslog Server and parse them. But my actual problem is, that i have some kind of wrong data:

Nov 17 08:10:06 konfwebrtc03 rtpengine[6017]: [f4490639-ab27-ccb5-bccb-c584d6a61d24] version=2, padding=0, count=1, payloadtype=200, length=3072, ssrc=1321979018, ntp_sec=3656736577, ntp_fractions=3918985859, rtp_ts=870058915, sender_packets=958, sender_bytes=153280, ssrc=604871110, fraction_lost=16777216, packet_loss=16777216, last_seq=32092, jitter=160, last_sr=0, delay_since_last_sr=0,
Nov 17 08:11:23 konfwebrtc03 rtpengine[6017]: [f4490639-ab27-ccb5-bccb-c584d6a61d24] version=2, padding=0, count=1, payloadtype=200, length=3072, ssrc=1321979018, ntp_sec=3656736654, ntp_fractions=3480899195, rtp_ts=870264179, sender_packets=2239, sender_bytes=358240, ssrc=604871110, fraction_lost=16777216, packet_loss=33554432, last_seq=35936, jitter=160, last_sr=0,
delay_since_last_sr=0,

There are only a few lines with so wrong data (16777216 packets lost, with 958 packets sent . . .)
Also, i have some differences between two lines, is the rtcp Log for the tow legs apart? One line for Client - RTPengine and one line for RTPenginge - Asterisk?

**Comment by inf265** [comment] 2015-11-17 12:10
Hi, this feature came from us 1&1 (me). I had a look at it briefly and I cannot see an error in my tests. Anyway, could you please make a tcpdump and grab all RTCP packets to verify if the content of the packet on the wire equals the content of the output of the rtpengine log ? Thanks.

**Comment by qmex-mp** [comment] 2015-11-17 14:04
Its hard to find something equal. Sender Reports from Client to RTPengine are more than confusing.
A few examples:

Real-time Transport Control Protocol (Sender Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Sender Report (200)
    Length: 12 (52 bytes)
    Sender SSRC: 0x8ad04f7a (2328907642)
    Timestamp, MSW: 761486227 (0x2d635b93)
    Timestamp, LSW: 3935657718 (0xea955ef6)
    [MSW and LSW as NTP timestamp: Mar 25, 2060 18:25:23.916341000 UTC]
    RTP timestamp: 2810688139
    Sender's packet count: 465778021
    Sender's octet count: 3154437738
    Source 1
        Identifier: 0xa6f12abd (2800822973)
        SSRC contents
            Fraction lost: 238 / 256
            Cumulative number of packets lost: 3882050
        Extended highest sequence number received: 1288746248
            Sequence number cycles count: 19664
            Highest sequence number received: 46344
        Interarrival jitter: 2427351931
        Last SR timestamp: 338305447 (0x142a21a7)
        Delay since last SR timestamp: 245859155 (3751512 milliseconds)

Real-time Transport Control Protocol (Sender Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Sender Report (200)
    Length: 12 (52 bytes)
    Sender SSRC: 0x8ad04f7a (2328907642)
    Timestamp, MSW: 1812769156 (0x6c0ca984)
    Timestamp, LSW: 4130848381 (0xf637be7d)
    [MSW and LSW as NTP timestamp: Jul 18, 2093 09:27:32.961788000 UTC]
    RTP timestamp: 3748421911
    Sender's packet count: 1095856563
    Sender's octet count: 1269942663
    Source 1
        Identifier: 0x62f161db (1659986395)
        SSRC contents
            Fraction lost: 223 / 256
            Cumulative number of packets lost: 7990853
        Extended highest sequence number received: 2586046967
            Sequence number cycles count: 39459
            Highest sequence number received: 61943
        Interarrival jitter: 3701307827
        Last SR timestamp: 1966608118 (0x75380ef6)
        Delay since last SR timestamp: 1682777988 (25677154 milliseconds)

Real-time Transport Control Protocol (Sender Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Sender Report (200)
    Length: 12 (52 bytes)
    Sender SSRC: 0x8ad04f7a (2328907642)
    Timestamp, MSW: 1636003754 (0x61836faa)
    Timestamp, LSW: 2332455752 (0x8b067348)
    [MSW and LSW as NTP timestamp: Dec 11, 2087 11:57:30.543067000 UTC]
    RTP timestamp: 4027369266
    Sender's packet count: 3500117447
    Sender's octet count: 891850491
    Source 1
        Identifier: 0x23800161 (595591521)
        SSRC contents
            Fraction lost: 101 / 256
            Cumulative number of packets lost: -1862742
        Extended highest sequence number received: 3672999162
            Sequence number cycles count: 56045
            Highest sequence number received: 34042
        Interarrival jitter: 2316661826
        Last SR timestamp: 2805316698 (0xa735bc5a)
        Delay since last SR timestamp: 1906976269 (29098148 milliseconds)


Ideas?

**Comment by inf265** [comment] 2015-11-17 14:36
Oh I think you loose me... Is this the output from the wire ? I guess.
At least (without having a look into the code) the rtpengine just "parses" and prints out the received RTCP packets to the log. So if the clients are sending this data in rtcp, the problem is located at the client side not at the rtpengine.

**Comment by qmex-mp** [comment] 2015-11-17 14:41
Its wireshark. Client is Chrome with SIPML5.

**Comment by inf265** [comment] 2015-11-17 14:52
Ok so the data in wireshark equals the output in the rtpengine log ?

**Comment by qmex-mp** [comment] 2015-11-17 15:01
Its hard to combine. But I cross- checked it. So, even it rtpengine reports fraction_loss=0, in wireshark I can see absolutely weird losses. Also with firefox. Also the timestamps are completely wrong:

MSW and LSW as NTP timestamp: May 14, 1975 21:12:58.352227000 UTC
MSW and LSW as NTP timestamp: Oct 23, 2025 21:50:38.590507000 UTC

Every Value is complete trash, one RTCP higher of lower by millions as in the RTCP packet before.

**Comment by inf265** [comment] 2015-11-17 15:30
Now you lost me completely.
One thing is the content of the the clients in the RTCP, the other thing is the output in the log in the rtpengine. If the content is equal (no matter if the values make sense), rtpengine works correct and the client is sending trash. If the values of a sent RTCP packet from the client (on the wire) differ from the content in the rtpengine log, rtpengine has a bug.

**Comment by qmex-mp** [comment] 2015-11-17 15:41
And they differ.
1. Clients sends data about packet loss that doenst exists. rtpengine logs fraction_lost=0.
2. Clients sends data about packet loss, that probably exists because we generated it. rtpengine logs fraction_lost=16777216 (which are exactly 24bit)

My next step is, to generate fixed loss (like 1, 2, 3, 10%) and see how the numbers will differ.

**Comment by inf265** [comment] 2015-11-17 18:45
Ok then there may be a problem in the rtpengine. Do you have an easy way for me to reproduce ?

**Comment by qmex-mp** [comment] 2015-11-18 07:57
It depends. What do you need to save time?
I can give you a PCAP, sure.
To reproduce it, you need a Kamailio configured as WebRTC Endpoint and a sipml5/jssip HTML5 Client (or use a Demo Site).

It its the easiest, i can give you access to our portal und to a dev Kamailio System so you can reproduce it yourself. I only need some contact to i cand send the credentials (its only dev, so no productive data).

**Comment by inf265** [comment] 2015-11-18 13:53
ok perfect. Contact ist myself. Which data you require additionally ? If company data, please send a private message to Frederic.Metz@1und1.de and I'll reply. One other question: I know everything is always very important but just to know, how important is a fix for this feature too you since I've got also other topics on my table.

**Comment by inf265** [comment] 2015-12-10 19:11
Thanks for your message and sorry for delay, there were some things I had to take care about.

**Comment by GGGO** [comment] 2016-01-03 21:39
Hi, 

I got same problem, the following patch fixed it.

--- rtcp.c.a
+++ rtcp.c.b

     *cdrbufcur += sprintf(*cdrbufcur,"ssrc=%u, fraction_lost=%u, packet_loss=%u, last_seq=%u, jitter=%u, last_sr=%u, delay_since_last_sr=%u, ",
                        ntohl(rr->ssrc),
-                       ntohl(rr->fract_lost),
-                       ntohl(packet_loss),
+                       rr->fract_lost,
+                       packet_loss,
                        ntohl(rr->last_seq),
                        ntohl(rr->jitter),
                        ntohl(rr->lsr),


I'm not sure but I think we need this too:
-                       common->length,
+                       ntohl(common->length),

**Comment by rfuchs** [comment] 2016-01-04 17:00
Looking at the code, @GGGO appears to be correct. Can you confirm @inf265 ?

**Comment by qmex-mp** [comment] 2016-02-08 15:57
Looks like this fixed it.
In the last Weeks we made some Tests and got really good and interesting data. From our Tests the System reported correct from 0 to more than 90% PL. So, everything is fine i think. Thank you all.

**Closed** 2016-02-08 19:19 UTC
