### ISSUE TITLE
build rtpengine without tests. 

### ISSUE THREAD

**Issue by johandeclercqdemocon** [sipwise/rtpengine#1091] opened 2020-10-16 13:29 UTC
Using latest version on github, using debian  buster, building without g729 support, 

issuing :  dpkg-buildpackage -d

fails with below error : 
"ok 1021 - received packet matches
ok 1022 - statistics - 'statistics' status
1..1022
Died at ../perl/NGCP/Rtpengine/AutoTest.pm line 260.
END failed--call queue aborted."

is there a way to build without tests or how do I fix this error ?

wkr,

**Comment by rfuchs** [comment] 2020-10-16 13:58
Please confirm that you're up to date on commits, in particular that 32cfb61e0b287f84b7be4d9c542e726548b28421 is included

**Comment by johandeclercqdemocon** [comment] 2020-10-16 14:23
Richard,

I took the one that is on git from this morning.

**Comment by rfuchs** [comment] 2020-10-16 15:02
Can't reproduce this on a stock Buster. What happens when you enter the `t` subdirectory and execute `make` ?

**Comment by johandeclercqdemocon** [comment] 2020-10-16 15:32
[output_of_make.txt](https://github.com/sipwise/rtpengine/files/5392647/output_of_make.txt)

**Comment by johandeclercqdemocon** [comment] 2020-10-16 15:32
so it seems to me that with make in t directory, there are no problems.

**Comment by rfuchs** [comment] 2020-10-16 15:40
Well that's even stranger then, because that's exactly what the build system executes when running the tests... Do you notice a delay between the `1..1022` and the `Died ...` line?

**Comment by johandeclercqdemocon** [comment] 2020-10-16 16:16
Nope.

Outlook voor iOS<https://aka.ms/o0ukef> downloaden
________________________________
Van: Richard Fuchs <notifications@github.com>
Verzonden: Friday, October 16, 2020 5:40:59 PM
Aan: sipwise/rtpengine <rtpengine@noreply.github.com>
CC: johandeclercqdemocon <johan@democon.be>; Author <author@noreply.github.com>
Onderwerp: Re: [sipwise/rtpengine] build rtpengine without tests. (#1091)


Well that's even stranger then, because that's exactly what the build system executes when running the tests... Do you notice a delay between the 1..1022 and the Died ... line?

**Comment by rfuchs** [comment] 2020-10-16 18:17
This is a bit of a shot in the dark, but try with the commit linked above (3893069) and see if that makes a difference.

**Comment by johandeclercqdemocon** [comment] 2020-10-17 11:30
Good morning Richard, 
the commit did not help. 

rtp recv 8 51661 330572070 168506581 adaca2a6bd9a063f262d2c2d263f069abda6a2acada1be831c3227222c2d21390c96b0a7a2acada0bb896c3124232c2d203a0afcb7a5a3acaca3a5b4d53425232c2c2325377c8abaa0adaca3a4b1ec093b202d2c222730168cb9a1adaca2a7b29c033e212d2c22263d1a86bfa6adacada6bf861a3d26222c2d213e039cb2a7a2acada1b98c163027222c2d203b09ecb1a4a3acada0ba8a7c3725232c2c232534
ok 1021 - received packet matches
ok 1022 - statistics - 'statistics' status
1..1022
Died at ../perl/NGCP/Rtpengine/AutoTest.pm line 260.
END failed--call queue aborted.
# Looks like your test exited with 22 just after 1022.
make[3]: *** [Makefile:113: daemon-tests] Error 22
rm control_ng.strhash.c sdp.strhash.c call_interfaces.strhash.c
make[3]: Leaving directory '/usr/src/rtpengine/t'
make[2]: *** [../lib/common.Makefile:4: all] Error 2
make[2]: Leaving directory '/usr/src/rtpengine/t'
make[1]: *** [Makefile:37: check] Error 2
make[1]: Leaving directory '/usr/src/rtpengine'
dh_auto_test: make -j48 check returned exit code 2
make: *** [debian/rules:25: build] Error 2
dpkg-buildpackage: error: debian/rules build subprocess returned exit status 2

**Comment by rfuchs** [comment] 2020-10-19 15:23
I've pushed a few more commits to the branch `rfuchs/1091`, in particular 4c77336 should be of interest. See if that fixes it for you.

**Comment by rfuchs** [comment] 2020-10-19 15:31
I've merged those commits to master now because those were definitely bugs. Please reopen if it doesn't fix it for you.

**Closed** 2020-10-19 15:30 UTC

**Comment by johandeclercqdemocon** [comment] 2020-10-19 15:32
Hello Richard,


I cloned the whole rfuchs/1091 branch and indeed the issue is now fixed.

Can you please integrate these in the master ?


wkr,
