### ISSUE TITLE
delay deleting session in mr9.5

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#1456] opened 2022-02-24 13:44 UTC
hello all

we are running Version: 9.5.2.0+0~mr9.5.2.0 git-v9.5-fabc5a12 on debian10, and when sending a delete from kamailio, we are seeing that the application lasts much more than the 5 secs expected to delete the session from memory

```
Feb 24 13:12:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [control] Received command 'offer' from 1.1.64.140:59583
Feb 24 13:12:39 mad-dedalus-ms-3 rtpengine[10307]: NOTICE: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] Creating new call
Feb 24 13:12:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [control] Replying to 'offer' from 1.1.64.140:59583 (elapsed time 0.000325 sec)
Feb 24 13:12:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [control] Received command 'delete' from 1.1.64.140:57247
Feb 24 13:12:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] Scheduling deletion of call branch '8dd7c1143fb01f75da3494a354ba920b-1ab4' (via-branch '') in 5 seconds
Feb 24 13:12:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [control] Replying to 'delete' from 1.1.64.140:57247 (elapsed time 0.000224 sec)
Feb 24 13:14:32 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] Call branch '8dd7c1143fb01f75da3494a354ba920b-1ab4' (via-branch '') deleted, no more branches remaining
Feb 24 13:14:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] Final packet stats:
Feb 24 13:14:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] --- Tag '8dd7c1143fb01f75da3494a354ba920b-1ab4', created 1:53 ago for branch '', in dialogue with ''
Feb 24 13:14:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] ------ Media #1 (audio over RTP/AVP) using unknown codec
Feb 24 13:14:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] --------- Port    1.1.65.22:22704 <> 2.2.175.148:51424, SSRC 0, 0 p, 0 b, 0 e, 113 ts
Feb 24 13:14:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] --------- Port    1.1.65.22:22705 <> 2.2.175.148:51425 (RTCP), SSRC 0, 0 p, 0 b, 0 e, 113 ts
Feb 24 13:14:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] --- Tag '', created 1:53 ago for branch '', in dialogue with '8dd7c1143fb01f75da3494a354ba920b-1ab4'
Feb 24 13:14:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] ------ Media #1 (audio over RTP/AVP) using unknown codec
Feb 24 13:14:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] --------- Port    1.1.65.22:22688 <>                :0    , SSRC 0, 0 p, 0 b, 0 e, 113 ts
Feb 24 13:14:39 mad-dedalus-ms-3 rtpengine[10307]: INFO: [c6e06950-079e-419f-92d1-ed0c73c5c4b1]: [core] --------- Port    1.1.65.22:22689 <>                :0     (RTCP), SSRC 0, 0 p, 0 b, 0 e, 113 ts
```

we are running the rtpengine with this options in the config file
```
[rtpengine]

table = 1
no-fallback = true

interface = 1.1.65.22

listen-ng = 1.1.64.133:7772
listen-tcp = 1.1.64.133:7771
listen-udp = 1.1.64.133:7771

timeout = 300
silent-timeout = 3600
tos = 184
delete-delay = 5

port-min = 10000
port-max = 60000

recording-dir = /var/log/record
recording-method = pcap
recording-format = raw

log-level = 6
log-facility = local7
log-facility-cdr = local6
log-facility-rtcp = local5
```

are we missing somthing in the setup? is it a known issue?
thanks a lot and regards
david

**Comment by rfuchs** [comment] 2022-02-24 14:41
How busy is your rtpengine installation? Delayed deletions are done in a single thread (together with other timers, like handling RTP timeouts), and so if there's lots of them or if that thread is busy doing other things, then the deletions might be delayed.

**Comment by descartin** [comment] 2022-02-24 15:01
hello Richard

in terms of cpu the servers didnt seem too much overloaded

![image](https://user-images.githubusercontent.com/7767994/155549288-12640342-f167-4840-b684-99e5f401a261.png)

do you want me to check any particular measure?
this thread uses a specific vCPU?

thanks a lot and regards
david

**Comment by rfuchs** [comment] 2022-02-24 15:18
The thread is marked as `poller timer` in the thread comm, which you can see with `ps -ecL` for example. Check the CPU usage of that thread, or perhaps even attach an strace to it (using the thread ID, not the process ID)

**Comment by descartin** [comment] 2022-02-25 15:22
hello Richard

i see this 
```
ps -ecL | grep "17616 "
17616 17616 RR  129 ?        00:00:00 rtpengine
17616 17617 RR  129 ?        00:00:00 signal handler
17616 17618 RR  129 ?        00:00:58 poller timer
17616 17619 RR  129 ?        00:00:00 load monitor
17616 17620 RR  129 ?        00:00:00 ICE
17616 17621 RR  129 ?        00:01:50 poller
17616 17622 RR  129 ?        00:01:51 poller
....
```
and when having around 3000 simultaneous calls and around 50 calls per second hitting the rtpengine, i see this usage for the poller timer
root@mad-dedalus-ms-3 system# ps -eLo pid,ppid,lwp,nlwp,osz,rss,ruser,pcpu,stime,etime,args | grep "17616     1 17618" | grep -v grep
17616     1 17618  102  - 239204 root     **1.7** 14:14       59:22 /usr/sbin/rtpengine -f --pidfile /var/run/ngcp-rtpengine1-daemon.pid --config-file /etc/rtpengine/rtpengine1.conf --table 1

i have 2 cpu sockets on that machine. If i configure the rtpengine to run in the same CPU(s) than the interface interrupts, the %si of the top is over 10%
```
top - 15:07:13 up 4 days, 41 min,  2 users,  load average: 1.03, 1.09, 1.19
Tasks: 282 total,   2 running, 280 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.5 us,  2.7 sy,  0.0 ni, 83.8 id,  0.1 wa,  0.0 hi, 11.9 si,  0.0 st
MiB Mem : 128922.1 total, 122198.2 free,   1013.7 used,   5710.1 buff/cache
MiB Swap:   9537.0 total,   9537.0 free,      0.0 used. 125643.4 avail Mem 
```
and if i configure the rtpengine to run in cpu0 with numactl and i use the smp affinity to control interface interrupts with CPU1, it's reduced to ~6-7

```
top - 15:08:38 up 4 days, 42 min,  2 users,  load average: 1.58, 1.27, 1.24
Tasks: 283 total,   1 running, 282 sleeping,   0 stopped,   0 zombie
%Cpu(s):  1.4 us,  3.0 sy,  0.0 ni, 89.0 id,  0.0 wa,  0.0 hi,  6.6 si,  0.0 st
MiB Mem : 128922.1 total, 122137.9 free,   1018.1 used,   5766.1 buff/cache
MiB Swap:   9537.0 total,   9537.0 free,      0.0 used. 125638.9 avail Mem 
```
```
14:54:02     CPU    %usr   %nice    %sys %iowait    %irq   %soft  %steal  %guest  %gnice   %idle
14:54:05     all    1.54    0.00    3.76    0.00    0.00    7.20    0.00    0.00    0.00   87.50
14:54:05       0    1.57    0.00    7.23    0.00    0.00    6.92    0.00    0.00    0.00   84.28
14:54:05       1    0.86    0.00    0.43    0.00    0.00   14.16    0.00    0.00    0.00   84.55
14:54:05       2    3.01    0.00    8.03    0.00    0.00    0.00    0.00    0.00    0.00   88.96
14:54:05       3    0.00    0.00    0.00    0.00    0.00   41.01    0.00    0.00    0.00   58.99
14:54:05       4    2.72    0.00    5.44    0.00    0.00    0.00    0.00    0.00    0.00   91.84
14:54:05       5    0.41    0.00    0.82    0.00    0.00   19.26    0.00    0.00    0.00   79.51
14:54:05       6    3.01    0.00    4.68    0.00    0.00    0.00    0.00    0.00    0.00   92.31
14:54:05       7    0.00    0.00    0.00    0.00    0.00   34.46    0.00    0.00    0.00   65.54
14:54:05       8    1.98    0.00    5.94    0.00    0.00    0.00    0.00    0.00    0.00   92.08
14:54:05       9    0.00    0.00    0.00    0.00    0.00   16.67    0.00    0.00    0.00   83.33
14:54:05      10    2.67    0.00    5.00    0.00    0.00    0.00    0.00    0.00    0.00   92.33
14:54:05      11    0.00    0.00    0.72    0.00    0.00   19.00    0.00    0.00    0.00   80.29
14:54:05      12    2.36    0.00    6.42    0.00    0.00    0.00    0.00    0.00    0.00   91.22
14:54:05      13    0.00    0.00    1.23    0.00    0.00    6.17    0.00    0.00    0.00   92.59
14:54:05      14    2.36    0.00    5.74    0.00    0.00    0.00    0.00    0.00    0.00   91.89
14:54:05      15    0.75    0.00    1.50    0.00    0.00   10.49    0.00    0.00    0.00   87.27
14:54:05      16    2.68    0.00    5.70    0.00    0.00    0.00    0.00    0.00    0.00   91.61
14:54:05      17    0.00    0.00    0.39    0.00    0.00    1.95    0.00    0.00    0.00   97.67
14:54:05      18    1.35    0.00    5.41    0.00    0.00    0.00    0.00    0.00    0.00   93.24
14:54:05      19    1.08    0.00    5.04    0.00    0.00   14.75    0.00    0.00    0.00   79.14
14:54:05      20    2.02    0.00    4.04    0.00    0.00    0.00    0.00    0.00    0.00   93.94
14:54:05      21    2.36    0.00    4.38    0.00    0.00    0.00    0.00    0.00    0.00   93.27
14:54:05      22    2.33    0.00    5.32    0.00    0.00    0.00    0.00    0.00    0.00   92.36
14:54:05      23    1.67    0.00    2.34    0.00    0.00    0.00    0.00    0.00    0.00   95.99
```

However, i still see there are problems to delete the sessions after the scheduled 5 secs.

The poller timer would be run under a single vcpu? (i see cpu 0 with 6.92 %soft, and the interfaces are under odd vcpus)

thanks a lot and regards
david

**Comment by descartin** [comment] 2022-03-09 09:40
hello Richard

sorry for the delay
i see these messages
Mar  8 08:12:40 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Increasing timer run interval to 2 seconds
Mar  8 09:01:05 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Increasing timer run interval to 4 seconds
Mar  8 09:10:41 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Increasing timer run interval to 8 seconds
Mar  8 10:28:27 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Increasing timer run interval to 16 seconds
Mar  8 13:17:59 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Increasing timer run interval to 32 seconds
Mar  8 18:41:20 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Decreasing timer run interval to 16 seconds
Mar  8 20:01:10 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Decreasing timer run interval to 8 seconds
Mar  8 20:01:18 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Decreasing timer run interval to 4 seconds
Mar  8 20:21:17 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Decreasing timer run interval to 2 seconds
Mar  8 20:21:42 mad-dedalus-ms-3 rtpengine[17616]: INFO: [core] Decreasing timer run interval to 1 seconds

this is done for hardware limitations? can be configured?

thanks a lot and regards
david

**Comment by rfuchs** [comment] 2022-03-09 13:03
This is not configurable. If the timer takes longer than 10% of the timer interval to run (e.g. longer than 0.8 seconds if the interval is 8 seconds) then the interval is doubled (and halved again if the timer runs quickly). This is to prevent the timer thread clogging up a CPU core with high CPU usage. The timer running continuously would also affect the performance of the rest of the daemon as it accesses internal structures while it's running.

You should probably investigate why the timer takes so long to run. Often this is because there's too many calls that have run into an RTP media timeout and need to be closed (which in turn can be because of missing `delete` in the signalling). Or perhaps your vCPU just isn't giving you enough clock cycles. Or something else is tying up the timer thread (XMLRPC callbacks?)

Anyway, looks like the code is working as intended, therefore closing.

**Closed by rfuchs** 2022-03-09 13:03 UTC
