### ISSUE TITLE
Compliing  on CentOS Linux release 7.6.1810 

### ISSUE THREAD

**Issue by olegans1972** [sipwise/rtpengine#788] opened 2019-06-03 11:01 UTC

**Comment by olegans1972** [comment] 2019-06-03 11:03
[root@rsww daemon]# make
make rtpengine rtpengine.8
make[1]: Entering directory `/usr/local/src/rtpengine/daemon'
cc  -g -Wall -Wstrict-prototypes -pthread -fno-strict-aliasing -std=c99 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include   -pthread -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include       -pthread     -I/usr/include/libxml2   -I/usr/include/libxml2     -pthread -I/usr/include/json-glib-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include     -DWITH_IPTABLES_OPTION -I. -I../kernel-module/ -I../lib/ -I../include/ -D_GNU_SOURCE -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg   -I/usr/include/ffmpeg     -DWITH_TRANSCODING -DHAVE_BCG729   -I/usr/include/mysql -I/usr/include/mysql/mysql -DRE_PLUGIN_DIR="\"/usr/lib/rtpengine\"" -DRTPENGINE_VERSION="\"git-master-7ad9906\"" -O3 -o rtpengine main.o kernel.o poller.o aux.o control_tcp.o call.o control_udp.o redis.o bencode.o cookie_cache.o udp_listener.o control_ng.strhash.o sdp.strhash.o stun.o rtcp.o crypto.o rtp.o call_interfaces.strhash.o dtls.o log.o cli.o graphite.o ice.o media_socket.o homer.o recording.o statistics.o cdr.o ssrc.o iptables.o tcp_listener.o codec.o load.o dtmf.o timerthread.o media_player.o loglib.o auxlib.o rtplib.o str.o socket.o streambuf.o ssllib.o dtmflib.o codeclib.o resample.o -lm -lglib-2.0   -pthread -lgthread-2.0 -lglib-2.0   -lz   -lpcre   -lcrypto   -lssl -lcrypto   -levent_pthreads -levent   -lpcap -lxmlrpc_client   -lxmlrpc   -lxmlrpc_util   -lhiredis -ljson-glib-1.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0   -lip4tc -lip6tc   -lavcodec   -lavformat   -lavutil   -lswresample   -lavfilter   -L$(exec_prefix)/lib64 -lspandsp -ltiff -lm   -lbcg729   -L/usr/lib64/ -lmariadb -lz -ldl -lm -lpthread -lssl -lcrypto
/bin/sh: exec_prefix: command not found
codec.o: In function `__dtmf_detect':
/usr/local/src/rtpengine/daemon/codec.c:1381: undefined reference to `dtmf_rx_fillin'
collect2: error: ld returned 1 exit status
make[1]: *** [rtpengine] Error 1
make[1]: Leaving directory `/usr/local/src/rtpengine/daemon'
make: *** [all] Error 2



I do not understand what you need. Which lib?

**Comment by rfuchs** [comment] 2019-06-03 12:27
Duplicate of #787

**Closed by rfuchs** 2019-06-03 12:27 UTC
