### ISSUE TITLE
RTPengine stops responding after Redis errors

### ISSUE THREAD

**Issue by agrigorjevs** [sipwise/rtpengine#1423] opened 2022-01-03 11:24 UTC
Hello,

We have encountered an issue where rtpengine stops responding to any requests and stops writing logs after receiving such errors about Redis connection:

ERR: [core] Failed to connect to Redis 10.180.82.16:60389, error: Protocol error, got "H" as reply type byte

These errors are received because Redis was not available and it is running in Kubernetes in our case - it seems that Kubernetes load balancer responds with HTTP errors during Redis unavailability and it causes rtpengine to hang after ~30 seconds of receiving such errors.

Expected behaviour would be for rtpengine to continue trying to reconnect to Redis, and not hang because of such errors.

P.S. no-redis-required is enabled in rtpengine config, and such issue does not happen if connecting to Redis directly without load balancer/proxy.

version 9.5.2.3+0~mr9.5.2.3 git-mr9.5.2-ff904a07

**Comment by rfuchs** [comment] 2022-01-04 14:00
Can you tell at which point it gets stuck? When stuck, kill it with SIGABRT to make it produce a core dump. Then load up the core dump in gdb and post the output of `thread apply all bt`

**Comment by agrigorjevs** [comment] 2022-01-12 15:06
@rfuchs sorry for the long delay, had to set up environment and run some tests to reproduce this issue.

I have no idea how to kill it with SIGABRT and get coredump, since rtpengine is running as Docker container in our environment, but I've done some more debug on the issue to understand what's the cause.

The issue is not relevant to the specific error log message I posted above, but it's an issue on trying to re-establish connection with Redis when you have any kind of TCP balancer in between (rtpengine -- balancer -- Redis).
The thing is, the balancer will try to connect to backend (Redis) for a while before timing out the client connection, and rtpengine in meanwhile stops accepting new ng requests (before the connection to Redis does not get timed-out). I believe the ng requests get buffered and waiting for Redis to become available.

In environment with connection to Redis directly this issue does not happen, because the connections to Redis get rejected, and therefore it just continues to respond to requests.

When this happens at a higher loads rtpengine can be stuck when re-establishing the connection to Redis server and then it is not accepting any more requests on the ng-protocol interface (UDP), thus not answering to any kamailio pings or other requests until service restart. But at the same time it is receiving requests to http interface successfully.
The load that causes this is around 0.04 ng requests/second or 3 CPS (in total, if that matters).
At a lower workload it may start working again after Redis is up, but still, while Redis is not available, rtpengine stops responding to any ng requests.

So to conclude - when the connection from rtpengine to Redis is hanging, rtpengine stops responding to ng requests (after the buffer is full, I believe)

**Comment by rfuchs** [comment] 2022-01-12 15:52
Ah ok, yes that makes more sense. It's probably caused by the lock on the Redis context being held while the connection attempt is in progress. The connection attempt is done in blocking mode so the lock remains held while it's in progress. There's a `redis-connect-timeout` option (defaults to 1 second) and a `redis-command-timeout` option (defaults to unlimited), but these are handled by `hiredis` internally so I can't guarantee that they always work as expected.

There's currently no support for handling non-responsive Redis backends like this, e.g. by fireing requests in a non-blocking way.

**Comment by agrigorjevs** [comment] 2022-01-13 09:17
Ok, got it. Played with different redis-connect-timeout and redis-cmd-timeout values, and setting them to 50ms works well in our environment, does not cause hanging issue anymore and should be sufficient for our setup.

Thank you!

**Comment by rfuchs** [comment] 2022-01-13 15:45
Closing the issue then

**Closed by rfuchs** 2022-01-13 15:45 UTC
