### ISSUE TITLE
Sequence errors

### ISSUE THREAD

**Issue by saraxxin** [sipwise/rtpengine#715] opened 2019-02-26 11:57 UTC
Hi.

I am running rtpengine in kernal mode using Debian 9 but am finding that I often get sequence errors.
Is there something I can do to mitigate this on rtpengine?

I don't see anything coming up on the logs for it.

**Comment by rfuchs** [comment] 2019-02-26 13:31
What's a sequence error?

**Comment by saraxxin** [comment] 2019-02-26 13:50
@rfuchs it's what I am seeing on Wireshark when doing an rtp analysis on the pcap. 
![image](https://user-images.githubusercontent.com/7115732/53417179-ae84b880-39dd-11e9-8b98-8c54fe9fd70f.png)

Perhaps a little more helpful info is that one of my providers insists on sending calls in with a ptime of 60 rather than 20 and so I have an asterisk machine that repacketizes it to 20ms before it reaches rtpengine. 
I've attached a pcap where you'll be able to see it.

[2e70e083-b46f-1237-3f81-002590ebc304.zip](https://github.com/sipwise/rtpengine/files/2905748/2e70e083-b46f-1237-3f81-002590ebc304.zip)

**Comment by rfuchs** [comment] 2019-02-26 14:06
Do you have a pcap of the other side of the call as well? Ideal would be one done on the rtpengine machine showing both streams in and out, together with a debug log for the same call.

**Comment by saraxxin** [comment] 2019-02-26 14:16
Hi. Yes I do. Please see below.

[221e33df3ce6aa2c5ff812b544e85a4f@sbc.convergedgroup.co.za.zip](https://github.com/sipwise/rtpengine/files/2905865/221e33df3ce6aa2c5ff812b544e85a4f%40sbc.convergedgroup.co.za.zip)

**Comment by rfuchs** [comment] 2019-02-26 14:25
Looks like the packets are received out of order. Are you running rtpengine on a VM?

**Comment by saraxxin** [comment] 2019-02-26 14:40
Hi.

I have tried on both a VM and on a physical. It is currently on a physical. Perhaps I am missing it but I don't see the out of order packets on the pcap I sent last. I dropped you a mail if you could perhaps check it out?

**Comment by rfuchs** [comment] 2019-02-26 15:48
No I mean received out of order by the client (or by Wireshark), as seen in the first pcap. The repacketisation you mentioned seems to be a factor here, as Asterisk seems to send 60 ms worth of audio in a spurt of three 20 ms packets, which are received (by rtpengine) pretty much simultaneously. And as rtpengine forwards them as soon as it receives them, due to how they're processed internally it's possible that they get reordered here. I don't think there's much that can be done here, and I also don't think it should be a problem for the receiving RTP client.

I didn't get an email btw.

**Comment by rfuchs** [comment] 2019-03-04 14:46
Closing as this is not a bug.

**Closed by rfuchs** 2019-03-04 14:46 UTC
