### ISSUE TITLE
regression in 9.5.x and 10.x probably regarding ROC reset on re-INVITE handling

### ISSUE THREAD

**Issue by henningw** [sipwise/rtpengine#1443] opened 2022-02-10 20:58 UTC
**There seems to be a regression introduced in 9.5.x and 10.x branches, probably regarding ROC reset on re-INVITE handling.**

Observed behaviour:

- Call is established from MS Teams infrastructure towards SBC
- Call works with two way audio with SRTP
- after 27 minutes there is a re-INVITE which identical SDP to the original INVITE
- on version 8.5.7 the audio stays two way, call can continue
- on version 9.5.2 and 10.2 the audio goes one-way (audio from B to A side is gone), no recovery, call is broken

Further research showed this might be an issue with MS Teams (translated from german discussion):

> This is usually caused by Crypto Key being reset on the SBC side for Re-Invite. In this case, the SBC must also be configured to reset the Rollover Counter (ROC) to 0, otherwise the SBC will not be able to decrypt packets sent by Teams media processors. Engineering comments: we support SRTP rekey in renegotiation, but ROC MUST be reset to 0, otherwise packets will be discarded by MP, as we expect with this rekey, SRTP ROC will be reset to 0 (this is the grey area of RFC, as either resetting/keeping the current ROC is OK). On our side, we reset ROC to 0 when a new key is issued. 

This disussion is about half a year old and might be not accurate anymore. Nevertheless it works with the old version and not with the new. Debugging output from proc below. Further debug logs available if necessary. Thank you.

**8.5.7 /proc/rtpengine/0/list before**

local inet4 XXX.XXX.97.175:30070
       src inet4 XXX.XXX.97.175:30090
       dst inet4 52.113.112.126:51912
    stats:             12965188 bytes,                75379 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:             12965188 bytes,                75379 packets
        RTP payload type   9:                    0 bytes,                    0 packets
        RTP payload type  13:                    0 bytes,                    0 packets
        RTP payload type  18:                    0 bytes,                    0 packets
        RTP payload type  97:                    0 bytes,                    0 packets
        RTP payload type 103:                    0 bytes,                    0 packets
        RTP payload type 104:                    0 bytes,                    0 packets
        RTP payload type 111:                    0 bytes,                    0 packets
        RTP payload type 118:                    0 bytes,                    0 packets
  SSRC in: 48b13059
    SRTP encryption (outgoing) parameters:
        cipher: AES-CM-128
    master key: 58dc17f916ec3ad17bbad6800e078c93
   master salt: ba54db7cac82cbcd9afc1c9127ee
   session key: 25852fff7af363ffb1502a3d3f7bc008
  session salt: 7cdaf384f10c4d436ef131a9c076
  session auth: 6020165df5408e3c730558f41177d34b446a0d69
           ROC: 1
        HMAC: HMAC-SHA1
            auth tag length: 10
local inet4 XXX.XXX.97.175:30090
       src inet4 XXX.XXX.97.175:30070
       dst inet4 XXX.XXX.97.175:32886
    stats:              2696330 bytes,                14815 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:              2696330 bytes,                14815 packets
        RTP payload type   9:                    0 bytes,                    0 packets
  SSRC in: a51ee2b0
    SRTP decryption (incoming) parameters:
        cipher: AES-CM-128
    master key: a23d639aeaddc91c28bc6c6258093ab8
   master salt: 2054cfeb08a426da54322781170a
   session key: 38fb490742d80951eb4a02f87115859f
  session salt: 00d321942928cec2d4a9ee590a93
  session auth: 598991dbac8e6865dd92ca1a192315b483ac5204
           ROC: 0
        HMAC: HMAC-SHA1
            auth tag length: 10
    option: stun

**8.5.7 /proc/rtpengine/0/list after**

local inet4 XXX.XXX.97.175:30070
       src inet4 XXX.XXX.97.175:30090
       dst inet4 52.113.112.126:51912
    stats:              1717764 bytes,                 9987 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:              1717764 bytes,                 9987 packets
        RTP payload type   9:                    0 bytes,                    0 packets
        RTP payload type  13:                    0 bytes,                    0 packets
        RTP payload type  18:                    0 bytes,                    0 packets
        RTP payload type  97:                    0 bytes,                    0 packets
        RTP payload type 103:                    0 bytes,                    0 packets
        RTP payload type 104:                    0 bytes,                    0 packets
        RTP payload type 111:                    0 bytes,                    0 packets
        RTP payload type 118:                    0 bytes,                    0 packets
  SSRC in: 48b13059
    SRTP encryption (outgoing) parameters:
        cipher: AES-CM-128
    master key: 58dc17f916ec3ad17bbad6800e078c93
   master salt: ba54db7cac82cbcd9afc1c9127ee
   session key: 25852fff7af363ffb1502a3d3f7bc008
  session salt: 7cdaf384f10c4d436ef131a9c076
  session auth: 6020165df5408e3c730558f41177d34b446a0d69
           ROC: 1
        HMAC: HMAC-SHA1
            auth tag length: 10
local inet4 XXX.XXX.97.175:30090
       src inet4 XXX.XXX.97.175:30070
       dst inet4 XXX.XXX.97.175:32886
    stats:              1001000 bytes,                 5500 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:              1001000 bytes,                 5500 packets
        RTP payload type   9:                    0 bytes,                    0 packets
  SSRC in: a51ee2b0
    SRTP decryption (incoming) parameters:
        cipher: AES-CM-128
    master key: a23d639aeaddc91c28bc6c6258093ab8
   master salt: 2054cfeb08a426da54322781170a
   session key: 38fb490742d80951eb4a02f87115859f
  session salt: 00d321942928cec2d4a9ee590a93
  session auth: 598991dbac8e6865dd92ca1a192315b483ac5204
           ROC: 0
        HMAC: HMAC-SHA1
            auth tag length: 10
    option: stun

**9.5.2 /proc/rtpengine/0/list before**

local inet4 XXX.XXX.0.110:30314
       src inet4 XXX.XXX.0.110:30332
       dst inet4 52.112.97.239:49456
    stats:             12545164 bytes,                72937 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type   9:             12545164 bytes,                72937 packets
        RTP payload type  13:                    0 bytes,                    0 packets
        RTP payload type  18:                    0 bytes,                    0 packets
        RTP payload type  97:                    0 bytes,                    0 packets
        RTP payload type 103:                    0 bytes,                    0 packets
        RTP payload type 104:                    0 bytes,                    0 packets
        RTP payload type 111:                    0 bytes,                    0 packets
        RTP payload type 118:                    0 bytes,                    0 packets
  SSRC in: 188e2dcf
    SRTP encryption (outgoing) parameters:
        cipher: AES-CM-128
    master key: e44e0689de35ce2d004231d9e95db980
   master salt: f60858079bf902b5ae1e905a6d61
   session key: d771309a1b77756b8496bc3c2d30a511
  session salt: d122b1a352b18af578f6d32e34c5
  session auth: 7c30cb6f8db706a2aaeea48a1e1e0f838f0b77a7
           ROC: 1
        HMAC: HMAC-SHA1
            auth tag length: 10
local inet4 XXX.XXX.0.110:30332
       src inet4 XXX.XXX.0.110:30314
       dst inet4 XXX.XXX.0.110:33316
    stats:              3150966 bytes,                17313 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type   9:              3150966 bytes,                17313 packets
  SSRC in: 53557ed3
    SRTP decryption (incoming) parameters:
        cipher: AES-CM-128
    master key: 5563b50364a31795b4e8ceb4752851c8
   master salt: 4ba59d801fe5734d0793e3514d95
   session key: c045a80f7626c5c080f3c4eb90644a27
  session salt: 3139a85a3762579ceba59ea7cb91
  session auth: 20c589364a21d002b1aab7a501b87515b05a2d86
           ROC: 0
        HMAC: HMAC-SHA1
            auth tag length: 10
    option: stun

**9.5.2 /proc/rtpengine/0/list after**

local inet4 XXX.XXX.0.110:30314
       src inet4 XXX.XXX.0.110:30332
       dst inet4 52.112.97.239:49456
    stats:               242004 bytes,                 1407 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type   9:               242004 bytes,                 1407 packets
        RTP payload type  13:                    0 bytes,                    0 packets
        RTP payload type  18:                    0 bytes,                    0 packets
        RTP payload type  97:                    0 bytes,                    0 packets
        RTP payload type 103:                    0 bytes,                    0 packets
        RTP payload type 104:                    0 bytes,                    0 packets
        RTP payload type 111:                    0 bytes,                    0 packets
        RTP payload type 118:                    0 bytes,                    0 packets
  SSRC in: 188e2dcf
    SRTP encryption (outgoing) parameters:
        cipher: AES-CM-128
    master key: e44e0689de35ce2d004231d9e95db980
   master salt: f60858079bf902b5ae1e905a6d61
   session key: d771309a1b77756b8496bc3c2d30a511
  session salt: d122b1a352b18af578f6d32e34c5
  session auth: 7c30cb6f8db706a2aaeea48a1e1e0f838f0b77a7
           ROC: 0
        HMAC: HMAC-SHA1
            auth tag length: 10
local inet4 XXX.XXX.0.110:30332
       src inet4 XXX.XXX.0.110:30314
       dst inet4 XXX.XXX.0.110:33316
    stats:               161980 bytes,                  890 packets,                    0 errors
        RTP payload type   0:                    0 bytes,                    0 packets
        RTP payload type   8:                    0 bytes,                    0 packets
        RTP payload type   9:               161980 bytes,                  890 packets
  SSRC in: 53557ed3
    SRTP decryption (incoming) parameters:
        cipher: AES-CM-128
    master key: 5563b50364a31795b4e8ceb4752851c8
   master salt: 4ba59d801fe5734d0793e3514d95
   session key: c045a80f7626c5c080f3c4eb90644a27
  session salt: 3139a85a3762579ceba59ea7cb91
  session auth: 20c589364a21d002b1aab7a501b87515b05a2d86
           ROC: 0
        HMAC: HMAC-SHA1
            auth tag length: 10
    option: stun

**Comment by henningw** [comment] 2022-02-10 21:14
Thanks, already feeling much better regarding the two days that my colleage and I spend on this.. As said, let me know if you like to have more debug information or we should try a patch on our test system etc..

**Comment by rfuchs** [comment] 2022-02-10 21:26
The problem is that I can't really reproduce it. A plain re-invite alone doesn't seem to do it. I started wondering if maybe the kernel module has something to do with it (i.e. if the problem disappears if the module isn't in use) but that also didn't pan out.

(I did find and fix one issue related to handling DTLS/SDES combinations, but that wasn't sufficient to eliminate this problem)

**Comment by henningw** [comment] 2022-02-11 08:25
With reproducing you mean in an independent test setup? Understood, yes this is probably difficult.
What about using e.g. git-bisect to find the change that introduced the regression and just revert it?

**Comment by rfuchs** [comment] 2022-02-11 17:44
I'm hoping that 7b525ed (together with 4a173c2 which is already merged) finally fixes this. Are you able to test?

**Comment by henningw** [comment] 2022-02-11 18:51
I can test, yes. Which branch, mr9.5.x with the two patches or another one?

**Comment by rfuchs** [comment] 2022-02-11 19:01
You can pull directly from `rfuchs/roc-fix` which is based on master, or apply those two commits to some other branch if you prefer. Up to you.

**Comment by henningw** [comment] 2022-02-11 19:02
Thanks, will be probably take 1-2 days due to the weekend.

**Comment by henningw** [comment] 2022-02-14 12:34
The 4a173c2 can be applied to mr9.5 LTS release (test is on a customer system). But the 7b525ed can not be applied. I could not  find the code in the call_timer function. I will test with the first patch for now, maybe you can have a look to it.

**Comment by rfuchs** [comment] 2022-02-14 13:09
> But the [7b525ed](https://github.com/sipwise/rtpengine/commit/7b525ed89c986b22470ce5e564f11a05ff4bbb03) can not be applied. I could not find the code in the call_timer function. I will test with the first patch for now, maybe you can have a look to it.

Yes you're right. 9.5 should not be affected by this. So perhaps the other commit fixes it for you.

**Comment by henningw** [comment] 2022-02-14 15:50
@rfuchs Unfortunately the patch does not seems to help, two calls were tested. 
root@sbct2:/home/henning# rtpengine -v
Version: 9.5.3.5-0+rtpengine9511+2 (actually branch from mr9.5 of today
Just testing with deactivated kernel mode.

**Comment by rfuchs** [comment] 2022-02-14 17:09
This seems to have an entirely different cause then. Post the entire log, perhaps there's a good reason why the crypto context is being reset.

**Comment by henningw** [comment] 2022-02-14 17:37
Please find attached the complete debug log from start of call to finish. I did a new call in kernel mode, just to be sure.

[gh-1443.txt.gz](https://github.com/sipwise/rtpengine/files/8062790/gh-1443.txt.gz)

**Comment by henningw** [comment] 2022-02-14 19:21
@rfuchs Just let me know if you need something else, or there is some issue with the debug log.

**Comment by rfuchs** [comment] 2022-02-15 15:57
Somehow I'm not getting the same behaviour when replaying this signalling locally.

I'm wondering if ICE has something to do with it. I see ICE being offered by your A side, and some initial ICE exchanges taking place, but then the answer instructs rtpengine to `ICE=remove` which subsequently (and correctly) leaves the re-offer without ICE.

Are you able to retest this with `ICE=force` instead of `ICE=remove` in the answer? Or perhaps with a non-ICE client as your A side?

**Comment by SirDMZ** [comment] 2022-02-16 00:34
Yup, that did the trick.
8.5 branch works with ICE=remove.
9.5 branch and 10.3 branch fail with ICE=remove. They work with ICE=force on the teams side.

**Comment by henningw** [comment] 2022-02-16 06:31
I can confirm that removing the ICE=remove fixes the issue. Thank you very much.

**Comment by rfuchs** [comment] 2022-02-16 12:53
Ok great, now to find out why that makes a difference :laughing:

**Comment by rfuchs** [comment] 2022-02-16 13:39
Can you post your config? The interface config in particular and whether the `sip-source` option is set.

**Comment by henningw** [comment] 2022-02-16 13:43
There is not that much in the cfg, but sure - rtpengine.conf:

```
[rtpengine]
table = 0
interface = XXX.XXX.0.111
listen-ng = 2223
timeout = 60
silent-timeout = 3600
tos = 184
port-min = 30000
port-max = 40000
```

**Comment by rfuchs** [comment] 2022-02-16 14:55
Ok I think I see it. Looks like a curious interaction between rtcp-mux and ICE. Will push some commits fixing this soon.

**Comment by rfuchs** [comment] 2022-02-16 15:22
I've pushed a few commits to branch `rfuchs/roc-fix-mr9.5` with the two linked above being the most important ones. This is on top of mr9.5, but will also be relevant to master. If you want to test to see if this fixes it for you, without having to change your signalling, then let me know how it goes. Otherwise I'll just merge them in.

**Comment by henningw** [comment] 2022-02-17 16:54
We observe now another issue with mr9.5 from a few days ago and the ICE=default fix. Now we are getting one way audio for calls in the other direction after reINVITE.
Initial debugging showed that rtpengine is changing media port towards B (ICE) side after obtaining reINVITE from A (no ICE) side. The crypto parameters stay unchanged. The A side keeps the same SDP for INVITE and reINVITE.
I will try to test the two patches later today.

**Comment by jamesfranck** [comment] 2022-02-22 13:57
Hello,
We're facing almost the same issue on our version 10.3.0.0+0~mr10.3.0.0
Can you release the same patch in the newer versions ?

Thanks in advance.

**Comment by rfuchs** [comment] 2022-02-22 15:17
I'm still waiting for confirmation from @henningw 

There were a few other somewhat related issues reported regarding re-invite handling. I've collected everything up in branch https://github.com/sipwise/rtpengine/tree/rfuchs/ice-roc-rtcp-fixes (on top of 9.5) for testing.

**Comment by henningw** [comment] 2022-02-22 15:19
@rfuchs I can probably do a quick verification this evening out of business hours.

**Comment by henningw** [comment] 2022-02-22 21:16
mr9.5 with the two commits seems to fix the issue. There is no one way audio even with ICE=remove after 27min reINVITE.

**Comment by rfuchs** [comment] 2022-02-23 16:08
Should be fixed now

**Closed by rfuchs** 2022-02-23 16:08 UTC

**Comment by nathanleyton** [comment] 2022-03-23 09:30
I am facing quite a similar issue to this, even after building from master. I see the ROC and v increase to 1. Audio can still be heard. After the increase if I use hold/off hold (i.e. an invite is sent) the audio is lost in one direction. The softphone itself continuously reports SRTP 7: authentication failure after we start sending the RTP packets again.  The timing that the ROC increases is quite random and I cannot link it to any SIP in particular. Here are the SRTP logs at the point it changes:-

`2022-03-23T08:53:45Z [1648025625.093483] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15000]: [srtp] Crypto debug: SSRC 4d072f14, seq 64788, prev seq 64787, s_l 64787, ROC 0, v 0, ext seq 64788, enc pl: e72c0ef8d6cce8fbdd000555f9002e7218e545b569052b474bd0452a21a08a2bf5959e69505a55ae57d0a631c347b51e1d512b1dc4a86966db25156933c50e5710d4d82deab8921be686f6554c43d15939933efde16f44f5a5f55158fc3265a32d35276ca954f742be5ed66e9955d0972a1f3dc54cf4fa3dfbfc7dbdc47321b8ff5075a8d445bb3649bef905e6d3adedfc6ee51fe94f03a5109d222910dfdb92, rcv hmac: 1c1e905bb264f82028fb, calc hmac: 1c1e905bb264f82028fb, dec pl: d5d5d5d5d4d5d5d5d5d5d5d55555d5d55555d555d5d5555555555555d555555555d55555d5d5555555d5d55555d55555d5d555d5d5d5d5d555555555d5d555d55555d5d5555555d55555d5d5d55555d5545555d5d5555555d5d5d5d5d5d5d5d5d555d5d5d5d5d55555d5d5d5d555555455d55555555555d55555555555555555555455d5d555555555d5d5555555d5d555555555555555d5d5d45555d5d555d5
2022-03-23T08:53:45Z [1648025625.715020] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15008]: [srtp] Crypto debug: SSRC 8a569c7f, seq 45695, prev seq 45694, s_l 45694, ROC 0, v 0, ext seq 45695, plain pl: 55d5d5555555d55555d5d5d5d5d5d5d555555555d5d5d5d5d5d555d55555d5d5d55555d555d55555d5d555d5d5d5d5d5d5d555d5d5d5d5d5d5d555d5d5d55555d5d5d5d5d5d5d5d5d5d5d555d5d55555d5d55555d5d5d5d5d5d5d5d5d5d5d5d5d5555555d5d5d5d55555555555d5d5d5d55555d55555555555d5d5d5d5d5d555555555d5d5d5d5d5d5555555d5d5d5d5555555d5d555d5d5d5d5d5d5d5d5d5d5, enc pl: b8bae9a376b90dcb4f37a93e585284e146463ed3c86b39833dd363aa21dbd7852226a10882657ec7f3405e6a6ed0999c36cc45077f79aac84b7fc9445ffa07e7536efbc56f4de5577f2c3641dd31646e9388135bfa5c5b47ed824d7cf21b915c3d70e976b087d1f0e9ee7d6c4fd949f6cb26e64c3396af2f50795ed20edc6400ca350ffa342f2a81d9e6f9d9caf051c233aab74120a22d040d22a5c8462374c9, auth: ec46c7b634b69e92e434
2022-03-23T08:53:50Z [1648025630.321078] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15001]: [srtp] Crypto debug: RTCP SSRC 142f074d, enc pl: 4c996ab52d6f64257ed32c72ab3f15167c541aa918a9a35f66268c2cccc9dfaa354d5c5c7463a5b3a851f93daeb56e5bdd8e69d5979b22b48000003f, idx 2147483711, rcv hmac: fe9d9ed461d46312d66b, calc hmac: fe9d9ed461d46312d66b, dec pl: 8a569c7f000000130000b36300000000000000000000000081ca00074d072f1401156e617468616e406e617468616e732d6c6170746f7000
2022-03-23T08:53:52Z [1648025632.238670] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15001]: [srtp] Crypto debug: RTCP SSRC 7f9c568a, idx 77, plain pl: e5e55ea03d0cc35c002fdfa000004ae500353ece0335d6af00000000000042ee000008265d60317801400b934d072f140000000b0000fe79000000665e9c007000043c9c81ca00058a569c7f010c6662663864376264623537360000, enc pl: 69d3bf92ba6eb327a89e90675bd481850541612e28a834b313dd492aabdaebd1745ef272d1533bc5ce12739cae93c51f3df14ebc2884de4b19aad646c6d88f27a7b8a207abd1c2379520007477c0903570012921ee8d746726f1a5ac, auth: 056988ffbdaeb67b135d
2022-03-23T08:53:55Z [1648025635.322613] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15000]: [srtp] Crypto debug: SSRC 4d072f14, seq 65300, prev seq 65299, s_l 65299, ROC 0, v 0, ext seq 65300, enc pl: a31271eecff92d721bf0cbfeb859bfda8c2aff80a32c634162779798267823cda3a12db454feaf75691e1f6ebcf40d6b2cc5682b4b06847734596565970d18c9989ce4454aa47f11297d78b2369a196530ddfde40b7ecbf799c375a826d34b5128980d60932f3598c6b48c7856b608b2d84ab8e1601f3b866caf2133759da4fcd68f0c9ee636739c86c0184275548d62cbe774b1c2c4774b7c61ab80a3b4c457, rcv hmac: 95dd0662dda0f66eef11, calc hmac: 95dd0662dda0f66eef11, dec pl: 55d4d4d4d5d5d5d5d5d5d55555d5d5d555545554555554545454555555555454555555555555d55555d555555555d4d5d5d5d5d4d5d5d4d4d4d5d4d4d4d4d4d5d5d5d5d555d5d55555d55555555555d5d555555555555555d55555d555555455d55555d5d5d5d5d5d5d5d5d5d55555d5d55555d5d55555d5d55555d5d55555555555d5d5d5d55555d5555555555454555554545455d5555555545455d5d5d5d5
2022-03-23T08:53:55Z [1648025635.897072] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15001]: [srtp] Crypto debug: RTCP SSRC 142f074d, enc pl: 43b151311283884587ccba2fbfd781bbd6640ea6048de8769c94cda3b1aa1d183bf3e1ff2003e504bc508d87c659be8adf9a226d7b6233d780000040, idx 2147483712, rcv hmac: a224b09882b80a03d9ef, calc hmac: a224b09882b80a03d9ef, dec pl: 8a569c7f000000130000b47900000000000000000000000081ca00074d072f1401156e617468616e406e617468616e732d6c6170746f7000
2022-03-23T08:53:55Z [1648025635.974714] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15008]: [srtp] Crypto debug: SSRC 8a569c7f, seq 46207, prev seq 46206, s_l 46206, ROC 0, v 0, ext seq 46207, plain pl: d5d5d555555555d5d5555555555555d5d5d5d5d555d5555555d5d555d555d5d5555555d555d5d5d555d5d555d5d5d5d5d5d5d5d5555555555555d5d5d555555555d5d5d5d55555555555555555d5d5d5d5d5d5d5d55555d5d5d555d5d555d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d5d55555d5d5d5d5d5d5d5d5d5d5555555d5d555d55555d5d5d5d5d5d555555555d55555d5d5d5d5d5d55555d5d5d5d5d5, enc pl: e6ad0f2eb9d1e9db5a3f058416fe4a6e2f5731ae66e5f019d784fa2c885d9f8327049b70ffadf240903f395323123171996993b8a2cf8b1f1756f4a6b1bade0f28975e2eb85b7551d867c3946d370cf9d2edabf0287d9d2e14e254626fde76c130a05f0208e6e69f596b1b20d5b030ce9e56a4511ad61fd71e6b923e73eacb8948cb2d65cc418a3a7de722946ed8b38c5565e1b6ed1bebaaab4d7f1e3f5885ce, auth: 45b5b3eed7d14b334ea4
2022-03-23T08:54:01Z [1648025641.854774] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15001]: [srtp] Crypto debug: RTCP SSRC 142f074d, enc pl: 341903979560d6dd80055a06857dbf6ffc87fcee98ae5a9088bf9bfeb8f724a2f022d04a40cb93f9de970a71b3dc0f7ea3d3615c61040d8a80000041, idx 2147483713, rcv hmac: 86f7775afc64290c38e3, calc hmac: 86f7775afc64290c38e3, dec pl: 8a569c7f000000130000b5a200000000000000000000000081ca00074d072f1401156e617468616e406e617468616e732d6c6170746f7000
2022-03-23T08:54:05Z [1648025645.552101] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15000]: [srtp] Crypto debug: SSRC 4d072f14, seq 276, prev seq 65811, s_l 275, ROC 1, v 1, ext seq 65812, enc pl: be89cf09f2a6392cd6055bca4b036516163fcf36239de6d278cba24803833e45f416c317e777fc3e5ee4fb60ee29fa2059994660c75c9968ce969e841d618ac62e7166da3d7136e38622c0c4aea02771ca6506557de14c973db132713a3511fd96e60e3cca4a5750a5d782b48ba4c8910ab9051a82e32efb027e29f18f4c95d978930da05ffda8e4370bc48ad10118cee7f91b5404e083911664ec75a561a56f, rcv hmac: da6902ca8c21cd11b8b6, calc hmac: da6902ca8c21cd11b8b6, dec pl: 555555555555d5d5d5d5d5d5d555d5d5d5d5d5d5d55555d5555555555555555555d5d5d555555555555455d5d5d5555555d5d5d5d5d5d5d5d5d5d5d4d4d5d4d5d5d5d4d4d5d5d5d5d5d5d5d5d5d5d5d555d55554d5555555d5d5555555d5d5d5d5d5d5555555555555555555555555555555d5d5d55555555555545454545454545455555555d5555555555555d5d55555d5555555555454555555d5555555d5
2022-03-23T08:54:05Z [1648025645.688356] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15001]: [srtp] Crypto debug: RTCP SSRC 7f9c568a, idx 78, plain pl: e5e55eadb027c7c4003183a000004d8200371a6c0335d6af00000000000042ee000008265d603178014d7eae4d072f140000000b0001011a000000675ea64ef70007613081ca00058a569c7f010c6662663864376264623537360000, enc pl: 0ada22d236ffe21c746e29f04b5bbdd8845b22ded96f2480e8f42189f3a13c75514da0c90dc6a2cb38c7748bb903a56ccfb487f56571aedadac80303258f274a535e1b9a5ec8f35cfd9902c2ccf9415655e4af366cb02f13c259aea8, auth: 524f12b1af66c4096ce3
2022-03-23T08:54:06Z [1648025646.274620] NOTICE: [b0ca7a3c-2528-123b-92bf-02438253f62a port 15008]: [srtp] Crypto debug: SSRC 8a569c7f, seq 46719, prev seq 46718, s_l 46718, ROC 0, v 0, ext seq 46719, plain pl: d5d555d5d55555d5d5555555555555d5d5d55555d5d555555555d5d55555d5d555d5d555d55555555555555555d5d5d555d5d5d5d555d5d555d5d5d5d5d5d5d5d5d5d5d5d5d55555d5d55555d5d5d55555d5d5d555d5d5d5d5d5d5d5d555555555d5d5d5d5d5d5d5d555d5555555d5d55555d5d5d5d5d5d5d5d5d555d555555555d5d5d5d5d5d5d5d555d55555d5d5d5d5d5d555d55555d5d5d5d5d555d5d5d5, enc pl: bae0fd5f0c638cee4ada2d9f6d10e6f819cdbae835cb6e3ef15dd8d0c4c9edd8f3d043bcf58c3edbce47217037ba29c1c8f696f11641c77508db79dfeac459f87ccd394bbaf9578623c2d9f8d05236aed887c17038a8641db0e795c4b28ab781cdd2b24910929b424844a6a03d377295cd7963fd0ff723fc5a12adb43be72f3e76b3676cebd77522c8e2903a7f718ef3fbcb12c573e966ae8c59c351e22d3bf3, auth: 048c8aaaeaade9b3b7d4
`

I have been trying to get around this issue for weeks now, I have tried all kinds of ICE configurations. See attached the pcap from homer (annoyingly homer split it to 2 as its a long call, also changed to txt so I can upload). 

[export_185510185-3857014022-1703875986@MSX187.gammatelecom.com (1).txt](https://github.com/sipwise/rtpengine/files/8331676/export_185510185-3857014022-1703875986%40MSX187.gammatelecom.com.1.txt)
[export_185510185-3857014022-1703875986@MSX187.gammatelecom.com.txt](https://github.com/sipwise/rtpengine/files/8331677/export_185510185-3857014022-1703875986%40MSX187.gammatelecom.com.txt)

You will see the only SIP is a re-invite which is happening quite a few minutes after the ROC increases. So in my case there is no call to rtpengine required for either offer or answer at the time. I have seen this happen from as little as 1 minute in to the call up to 30 mins, but eventually it always happens. It is only realised by users when they use hold after the ROC increases without using hold / off hold 2 way audio will remain through all the re-invites etc, even on very long calls. 

What other cases could cause such behaviour. 

Thank you for any help / advice you can give me.

**Comment by rfuchs** [comment] 2022-03-23 12:10
@nathanleyton In the log you posted the ROC increase is correct. SSRC 4d072f14 rolls over its RTP sequence number (exceeds 65535) and so the ROC must increase. Perhaps the softphone is not keeping track of the ROC correctly? You can verify the ROC by capturing the SRTP and running it through a decrypter manually (which requires access to the SRTP keys).

Unless this is actually an issue with the rtpengine code you should probably head for the mailing list with this and not re-use a probably unrelated Github issue.

**Comment by nathanleyton** [comment] 2022-03-23 12:25
Thanks for the tip. I will try and decrypt manually I didn't want to create a new issue as I thought it may be related to this as the outcome was so similar. I am able to replicate on Zoiper (All platforms), LinPhone and MicroSIP on windows, I guess all of them could have the same bug. I am no crypto expert but I will try and prove either way how this is happening. Thanks again
