### ISSUE TITLE
rtp timeout in ha scenario

### ISSUE THREAD

**Issue by hamedfaramarzi** [sipwise/rtpengine#522] opened 2018-04-10 13:28 UTC
Hello all,

I am using an HA/LB cluster between my private and public networks. In the rtpengine configuration, I have used like this:

rtpengine server 1 :  interface = pub:1/X;pub:2/Y;pub:3/Z;priv:1/A;priv:2/B;priv:3/C
rtpengine server 2 :  interface = pub:1/Y;pub:2/Z;pub:3/X;priv:1/B;priv:2/C;priv:3/A
rtpengine server 3 :  interface = pub:1/Z;pub:2/X;pub:3/Y;priv:1/C;priv:2/A;priv:3/B

and I have dummy interfaces with bgp preferences in each of the servers. In my kamailio configuration, I have modparam("rtpengine", "rtpengine_sock", ALL_SERVERS_WITH_SAME_WEIGHT) and "direction=pub direction=priv"  for example or vice versa.

In some cases, for example kamailio connect to rtpengine server 2, but by random (round robin nature of NAME:[PREFIX]/NAME) the interfaces of server 1 and server 3 are being selected (for example the first priv interface of server 1 and the first pub interface of server 3). It works fine, and there is no problem except for timeout. If the rtp dies, the others take control. 

But since the server 2 is the OWNer of call and there is no RTP media, it tear the call. I use it with long timeout, but I think may be it is a bug, or I am not using the standard way.

**Comment by rfuchs** [comment] 2018-04-16 15:07
Are you doing this using the live Redis updates (keyspace notifications) to achieve HA?

**Comment by hamedfaramarzi** [comment] 2018-04-16 15:57
Yes. The first one is listener to 2,3 and writer to 1. and so on. The problem is that because it is round robin, sometimes rtpengine server 1  selects pub:2/Y and prive:3/C. Then all traffic incoming from rtpengine 2 and all outgoing traffic going out from rtpengine 3. rtpengine 1 has no RTP traffic, so after timeout (60 sec) delete the key from radius, and the call drops. I increased the time-out but I think it is not the way.

**Comment by rfuchs** [comment] 2018-04-16 15:59
I don't think this is how it's supposed to work. Perhaps @smititelu can shed some light on it.

**Comment by hamedfaramarzi** [comment] 2018-04-16 16:01
* correction: delete the key from redis

**Comment by pkuzak** [comment] 2018-04-17 11:49
I don't know another solution than increasing the timeouts in your case. We are using this feature a bit differently. E.g. in our case, the owner of the call usually gets the traffic. We ensure this by different BGP priorities. So if Kamailio speaks to Server 1, Server 1 will get the RTP traffic, if it speaks to Server 2, Server 2 will get the RTP traffic, and so on. The backup or _FOREIGN_ sessions are only required if a server fails unexpectedly. E.g. if Server 1 fails in our scenario, we have at least one other server which backs up the sessions of Server 1 (let the backup be Server 2). So if Server 1 fails, the BGP route with the highest priority is no more valid. The BGP route with the next highest priority is configured on Server 2. So the RTP packets which usually were forwarded by Server 1 will now be send to Server 2, which will forward them on behalf of Server 1.
So actually it is not a bug but part of the feature. Back then when we implemented this we thought about migrating the ownership of a call/session based on whether there is RTP traffic or not. But we decided to not do it, as it would add complexity. 
I would also not say you are using it in a non standard way but as I said, in your use case I don't see another solution than increasing the timeouts. 
Does this info help you?

**Comment by pkuzak** [comment] 2018-04-17 13:37
I think you can use round robin in _rtpengine_, but not the _direction_ parameter in Kamailio's configuration file. E.g. you could configure on _rtpengine_

> rtpengine server 1 : interface = pub1:1/A;pub1:2/B;pub1:3/C;pub2:1/D;pub2:2/E;pub2:3/F;pub3:1/G;pub3:2/H;pub3:3/I
> rtpengine server 2 : interface = pub2:1/D;pub2:2/E;pub2:3/F;pub3:1/G;pub3:2/H;pub3:3/I;pub1:1/A;pub1:2/B;pub1:3/C
> rtpengine server 3 : interface = pub3:1/G;pub3:2/H;pub3:3/I;pub1:1/A;pub1:2/B;pub1:3/C;pub2:1/D;pub2:2/E;pub2:3/F

You do not need to change your module parameters. In above example configuration file, when Kamailio speaks for example to server 2, server 2 will pick up an interface out of _pub2_. Server 2 will be the owner of this session, server 1 and 3 will have this session listed as a _foreign_ session. Now it depends on your BGP priorities where the RTP traffic goes to. In our setup, the routes with the highest priorities for IPs D, E and F (which all belong to _pub2_ on all serves) point to server 2. There are also routes to server 1 and 3 for that IPs, but with lower BGP priorities. 

Currently, we are not using this (_round-robin_) in our production environment. We are going to use this if we need to extend the amount of sessions _rtpengine_ can handle without using the direction parameter. 
Do you require round robin in your scenario?
I guess it could also work with _direction_ parameter as you've written, but I think then you need to set the direction dependent on which _rtpengine_ is going to be used.  
For this HA scenario with Redis notifications, it is important that in _rtpengine_ configuration file there is a unique mapping between logical interface names and IPs. E.g. If there is _pub1:1/A_, there is no _pub1:1/B_ anywhere on any other server. Why is this so: 
For example you have:

> rtpengine server 1 : interface = pub1/A;pub2/B
> rtpengine server 2 : interface = pub1/B;pub2/A

What will happen is: If Kamailio establishes the session on server 1 _pub1_, in Redis it is stored that there is a session on _pub1_ (**Note, there is no info about the IP**). For relaying, IP A is used. 
If server 2 gets a Redis notification, it will establish the session also on _pub1_. But on server 2, IP B is assigned to _pub1_. Server 2 will expect RTP packets for that session on IP B instead of IP A. 

Puh, a bit of text. Could you follow?

**Closed** 2018-04-28 12:29 UTC
