### ISSUE TITLE
rtpEngine doesn't load foreign calls from Redis on startup

### ISSUE THREAD

**Issue by paulandrewhughes** [sipwise/rtpengine#277] opened 2016-09-29 01:10 UTC
I am using version mr4.5.1.1

When rtpEngine starts it loads calls its own calls from Redis however it doesn't load foreign calls.

If I have two instances running like this:-
server1% rtpengine --interface eth0/10.1.1.13 --listen-ng 10.1.1.13:1025 -f --port-min 10000 --port-max 65535 --redis=10.1.1.15:6380/2  -c 10.1.1.12:1026 -k 1

server2% rtpengine --interface eth0/10.1.1.13  --listen-ng 10.1.1.13:1025 -f --port-min 10000 --port-max 65535 --redis=10.1.1.15:6380/1  -c 10.1.1.14:1026 -k 2

Address 10.1.1.13 is only active on server 1.

A single call is made and it can be seen in the output of ./rtpengine-ctl on both rtpengines
server1# rtpengine-ctl -ip 10.1.1.12 -port 1026 list sessions all
callid:                                                      6756523 | deletionmark:  no | created:  1474043331 | proxy:10.1.1.13:43839 | redis_keyspace:2 | foreign:no
server2# rtpengine-ctl -ip 10.1.1.14 -port 1026 list sessions all
callid:                                                      6756523 | deletionmark:  no | created:  1474043331 | proxy:10.1.1.13:43839 | redis_keyspace:2 | foreign:yes

If rtpengine on server1 is restart then the session is reloaded.
However if rtpengine on server 2 is restarted then no sessions are loaded on startup.
./rtpengine-ctl -ip 10.1.1.14 -port 1026 list sessions all
No sessions on this media relay.

**Comment by rfuchs** [comment] 2016-09-30 15:46
This probably belongs in @pkuzak 's or @smititelu 's department

**Comment by smititelu** [comment] 2016-09-30 16:56
From what I know, this was not implemented in the main redundancy pull request #225.

Currently, no plans to implement it, from my side.

**Comment by pkuzak** [comment] 2016-10-10 12:29
@smititelu is right, it has not been implemented (yet). The main reason why it has not been implemented is to keep the start time of the _rtpengine_ fast. In our setup we have 6 media relays in a full redundant setup, each one handling up to 5k own calls (thus each one also has up to 25k foreign calls). If a restart is needed, it's faster to just load the own 5k calls instead of 30k calls (of which 25k might not be needed if everything is working fine). After some time (~ 3h in our setup), the restarted media relay is again in sync with all others, meaning it again knows about all foreign sessions. 
We might implement this feature in the future, but currently it is not our priority.

**Comment by rfuchs** [comment] 2016-10-11 19:33
Closing issue then - not a bug

**Closed by rfuchs** 2016-10-11 19:33 UTC
