### ISSUE TITLE
rtpengine sending incorrect payload to each sides doing transcoding

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#670] opened 2018-12-05 13:31 UTC
hello all

i'm using at this moment for testing transcoding Version: 6.5.2.0+0~mr6.5.2.0 git-v6.5-e900fed
and in the kamailio offer i'm setting just "codec-mask-PCMU codec-transcode-G729" for a call which comes with codec 0 to be transcoded to 18.

And it seems it goes well, but after the call is connected, the audio disappear after 4-5 secs, and i start to see that rtpengine is sending the inverse rtp payload it should.
I mean

A ---> rtpengine ---> B
Rtpengine should send G729 to B but sends G711
Rtpengine should send G711 to A but sends G729

this is the moment when it changes in B side
  497 7.420008342 2.2.2.2 → 10.100.10.70 UDP 74 55464 → 24126 Len=32
  498 7.424994281 10.100.10.70 → 2.2.2.2 UDP 74 24126 → 55464 Len=32
  499 7.439967403 2.2.2.2 → 10.100.10.70 UDP 74 55464 → 24126 Len=32
  500 7.444988330 10.100.10.70 → 2.2.2.2 UDP 74 24126 → 55464 Len=32
  501 7.460005776 2.2.2.2 → 10.100.10.70 UDP 74 55464 → 24126 Len=32
  502 7.464846427 10.100.10.70 → 2.2.2.2 UDP 214 24126 → 55464 Len=172
  503 7.479977908 2.2.2.2 → 10.100.10.70 UDP 74 55464 → 24126 Len=32
  504 7.484822336 10.100.10.70 → 2.2.2.2 UDP 214 24126 → 55464 Len=172
  505 7.500019929 2.2.2.2 → 10.100.10.70 UDP 74 55464 → 24126 Len=32
  506 7.504810381 10.100.10.70 → 2.2.2.2 UDP 214 24126 → 55464 Len=172
  507 7.520033141 2.2.2.2 → 10.100.10.70 UDP 74 55464 → 24126 Len=32

i add you the logs of a failed call, don't know if i may be missing something
https://pastebin.com/STY1snhC
Maybe it could be related to fall to userspace? i run the rtpengine without the option -F

thanks a lot and regards
david

**Comment by rfuchs** [comment] 2018-12-05 13:42
Is this the full log that includes the moment when you see this switch?

Does it make a difference if you run without kernel module (use `table = -1`)?

**Comment by descartin** [comment] 2018-12-05 14:45
yes it was, not using the kernel module it works it seems :) thanks a lot

**Comment by rfuchs** [comment] 2018-12-05 15:09
In that case, can you paste the contents of /proc/rtpengine/0/list while the problem is occurring?

**Comment by descartin** [comment] 2018-12-05 15:23
here you have

https://pastebin.com/0d45cWNF

**Comment by rfuchs** [comment] 2018-12-05 15:56
Hm what I'm missing here is the `option: transcoding` flag in the output. Are you perhaps running a newer version of the rtpengine daemon with an older version of the kernel module?

**Comment by descartin** [comment] 2018-12-05 16:04
i'm using
4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux
and
Version: 6.5.2.0+0~mr6.5.2.0 git-v6.5-e900fed

is that ok?

**Comment by rfuchs** [comment] 2018-12-05 16:40
I'm asking if the version of the kernel module matches the version of the daemon

**Comment by descartin** [comment] 2018-12-05 17:06
i'm probably not getting you :), but this is what i have for kernel module

root@rtpengine-transcoding:/var/log# modinfo xt_RTPENGINE
filename:       /lib/modules/4.9.0-7-amd64/updates/dkms/xt_RTPENGINE.ko
license:        GPL
depends:        x_tables
retpoline:      Y
vermagic:       4.9.0-7-amd64 SMP mod_unload modversions 
parm:           proc_uid:rtpengine procfs tree user id (uint)
parm:           proc_gid:rtpengine procfs tree group id (uint)
parm:           stream_packets_list_limit:maximum number of packets to retain for intercept streams (uint)
parm:           log_errors:generate kernel log lines from forwarding errors (bool)

for daemon

root@rtpengine-transcoding:/home/dedal/src/rtpengine/daemon# rtpengine -v
Version: 6.5.2.0+0~mr6.5.2.0 git-v6.5-e900fed

and our kernel for debian system
root@rtpengine-transcoding:/home/dedal/src/rtpengine/kernel-module# uname -a
Linux rtpengine-transcoding.bts.io 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

best regards

**Comment by rfuchs** [comment] 2018-12-06 07:43
The kernel module prints its own version into dmesg when it gets loaded. What does it say?

**Comment by descartin** [comment] 2018-12-11 14:18
sorry the delay, holidays here
here you have all the output to do not miss anything 

https://pastebin.com/FH1z3u1D

best regards

**Comment by rfuchs** [comment] 2018-12-18 16:23
I'm having a hard time reproducing this. Your kernel module seems to be an older version that doesn't support transcoding, even though the reported version string is correct. The kernel is warning about the module being loaded out-of-tree, which is suspicious. Double check and make sure that the sources are up to date, that the correct version is compiled (recompile to be sure), that the correct version is loaded, and that there aren't any extra older modules floating around that might get loaded inadvertently instead of the correct one.

**Comment by descartin** [comment] 2018-12-19 08:41
hello Richard

i installed it on a physical server and seems it worked fine. The previous setup was on an AWS server.

there might be something related to the server in AWS ¿?

anycase, i have now a machine running with 6.5.3 and tested transcoding running the instance kernelized and it switchs to transcoding mode ok.

i have some other questions related to the feature but i will ask in another issue when i have a big enough set of them

thanks for your assistance
david

**Comment by rfuchs** [comment] 2018-12-19 14:15
AFAIK it works just fine on AWS - plenty of people are using it. But I have no personal experience with it. I still suspect there's a booboo on your side that the wrong sources got compiled or the wrong module got loaded. Anyway, closing this since it's not a real bug.

**Closed by rfuchs** 2018-12-19 14:15 UTC
