### ISSUE TITLE
More than 30 duplicate packets detected, dropping packet to avoid potential loop

### ISSUE THREAD

**Issue by descartin** [sipwise/rtpengine#65] opened 2015-01-23 09:07 UTC
Dear all

one quick question again :)

sometimes we are seeing a message

rtpengine[27270]: [9b5f51fb-fc03-4d34-a79e-4c7e5401e638 port 13151] More than 30 duplicate packets detected, dropping packet to avoid potential loop

for several calls always involving a rtcp port, could you please check if this message can cause any special type of problem, or why could be happening?

thanks a lot and regards
david

**Comment by rfuchs** [comment] 2015-01-23 13:56
This is usually a signalling problem, where rtpengine ends up sending packets to itself, for example caused by the SDP from a single SIP packet rewritten by rtpengine more than once. The duplicate packet detection is a way for rtpengine to protect itself against that.

It's either that, or the client is actually sending duplicate packets, and lots of them. It shouldn't do that because the sequence number should always change, but broken clients certainly do exist.

You can find out the exact cause by digging deeper, look into the signalling and perhaps a packet dump of the involved media ports.

**Comment by caruizdiaz** [comment] 2015-01-26 21:38
This also happened to me, followed by no audio in any of the endpoints. 

<pre>
Too many packets in UDP receive queue (more than 50), aborting loop. Dropped packets possible
</pre>

Browser was FF35.1

**Comment by slavrov** [comment] 2015-03-11 09:28
got the same errors on sip+rtp <-> sip+rtp calls. after established call and successful 6 minutes conversation the callee stop hear caller and in rtpengine log got bunch of errors.
the bug is floating and we still can't reproduce it.

Mar 11 11:45:22 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060] Creating new call
Mar 11 11:45:29 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48898] Confirmed peer address as x.x.x.x:19290
Mar 11 11:45:29 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48878] Confirmed peer address as y.y.y.y:52862
Mar 11 11:45:31 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48879] Confirmed peer address as y.y.y.y:52863
Mar 11 11:45:33 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] Confirmed peer address as x.x.x.x:19291
Mar 11 11:48:03 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:08 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:13 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:18 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:23 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:28 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:33 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:38 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:43 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:48 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:53 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:48:58 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:03 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:08 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:13 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:18 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:23 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:28 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:33 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:38 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:43 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:48 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:53 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Mar 11 11:49:58 rtpengine-0-0 rtpengine[444]: [10a551661300356e4f97dad4773216cc@x.x.x.x:5060 port 48899] More than 30 duplicate packets detected, dropping packet to avoid potential loop

**Comment by olivermt** [comment] 2015-03-16 14:54
I am getting this dumped in the logs while the call is working just as it should, the loop is always on the video part, but not always on the same UAC (this is software cisco client <-> cisco EX90 desktop system).

https://gist.githubusercontent.com/olivermt/0983158a043f10a8018e/raw/b7e146e85c723ed99e315a8b91fb1f761f18d7a4/gistfile1.txt

I am not noticing any degraded quality or anything, should I just ignore it?

**Comment by rfuchs** [comment] 2015-03-16 14:57
I can't comment without knowing what kind of packets those are. Only way to know is through a packet capture.

**Comment by descartin** [comment] 2015-03-19 17:19
Hello Richard

in my case the issue happens with some traffic, in one side or both when after 150secs (30 packets per 5 secs/packet) we start to drop the rtcp we receive from a side and we dont send rtcp packets.

in my case seems there is no quality impact, but seems like the rtcp they send from a leg, b leg or both might be wrong for some reason.
i made a capture of those rtcp packets that are filtered

User Datagram Protocol, Src Port: 28823 (28823), Dst Port: 12965 (12965)
    Source Port: 28823 (28823)
    Destination Port: 12965 (12965)
    Length: 88
    Checksum: 0x0000 (none)
        [Good Checksum: False]
        [Bad Checksum: False]
    [Stream index: 0]
Real-time Transport Control Protocol (Sender Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Sender Report (200)
    Length: 12 (52 bytes)
    Sender SSRC: 0x21cd3f0a (567099146)
    Timestamp, MSW: 0 (0x00000000)
    Timestamp, LSW: 0 (0x00000000)
    [MSW and LSW as NTP timestamp: Jan  1, 1970 00:00:00.000000000 UTC]
    RTP timestamp: 5159680
    Sender's packet count: 32236
    Sender's octet count: 5153392
    Source 1
        Identifier: 0xf7cab477 (4157256823)
        SSRC contents
            Fraction lost: 0 / 256
            Cumulative number of packets lost: 0
        Extended highest sequence number received: 8554
            Sequence number cycles count: 0
            Highest sequence number received: 8554
        Interarrival jitter: 11
        Last SR timestamp: 0 (0x00000000)
        Delay since last SR timestamp: 0 (0 milliseconds)
Real-time Transport Control Protocol (Source description)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Source count: 1
    Packet type: Source description (202)
    Length: 6 (28 bytes)
    Chunk 1, SSRC/CSRC 0x21CD3F0A
        Identifier: 0x21cd3f0a (567099146)
        SDES items
            Type: CNAME (user and domain) (1)
            Length: 17
            Text: 9552@10.95.251.61
            Type: END (0)


User Datagram Protocol, Src Port: 28823 (28823), Dst Port: 12965 (12965)
    Source Port: 28823 (28823)
    Destination Port: 12965 (12965)
    Length: 88
    Checksum: 0x0000 (none)
        [Good Checksum: False]
        [Bad Checksum: False]
    [Stream index: 0]
Real-time Transport Control Protocol (Sender Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Sender Report (200)
    Length: 12 (52 bytes)
    Sender SSRC: 0x21cd3f0a (567099146)
    Timestamp, MSW: 0 (0x00000000)
    Timestamp, LSW: 0 (0x00000000)
    [MSW and LSW as NTP timestamp: Jan  1, 1970 00:00:00.000000000 UTC]
    RTP timestamp: 5199680
    Sender's packet count: 32486
    Sender's octet count: 5193392
    Source 1
        Identifier: 0xf7cab477 (4157256823)
        SSRC contents
            Fraction lost: 0 / 256
            Cumulative number of packets lost: 0
        Extended highest sequence number received: 8804
            Sequence number cycles count: 0
            Highest sequence number received: 8804
        Interarrival jitter: 13
        Last SR timestamp: 0 (0x00000000)
        Delay since last SR timestamp: 0 (0 milliseconds)
Real-time Transport Control Protocol (Source description)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Source count: 1
    Packet type: Source description (202)
    Length: 6 (28 bytes)
    Chunk 1, SSRC/CSRC 0x21CD3F0A
        Identifier: 0x21cd3f0a (567099146)
        SDES items
            Type: CNAME (user and domain) (1)
            Length: 17
            Text: 9552@10.95.251.61
            Type: END (0)
[RTCP frame length check: OK - 80 bytes]


i have been trying to capture in those cases the other part of the call but i'm not getting anything on the rtcp port.

regards
david

**Comment by rfuchs** [comment] 2015-03-19 17:30
Hm, I see that these RTCP packets use a zero NTP timestamp. The packet loop protection only looks at the first 16 bytes, which is just enough to include the NTP timestamp but doesn't include the RTP timestamp for RTCP. This could explain why these packets are seen as duplicates.

**Comment by descartin** [comment] 2015-03-19 17:39
I see, but i dont have clear if this is a failure or not, because according to rfc3550
6.4.1 SR: Sender Report RTCP Packet
"A sender that
      has no notion of wallclock or elapsed time MAY set the NTP
      timestamp to zero."

**Comment by rfuchs** [comment] 2015-03-19 17:40
Yes, I think an increase in the number of checked bytes should do the trick.

In call.h, you can change RTP_LOOP_PROTECT to 24 and see if that fixes it for you.

**Comment by descartin** [comment] 2015-03-23 11:47
Hello Richard

i made the change on one rtpengine, i recompiled it totally, and i dont see those message woth ntp timestamp 0 by now, but i still do see some blocks, of some Receiver Report messages like this

Real-time Transport Control Protocol (Receiver Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Receiver Report (201)
    Length: 7 (32 bytes)
    Sender SSRC: 0x1d1c4454 (488391764)
    Source 1
        Identifier: 0x253c405e (624705630)
        SSRC contents
            Fraction lost: 0 / 256
            Cumulative number of packets lost: 0
        Extended highest sequence number received: 24562
            Sequence number cycles count: 0
            Highest sequence number received: 24562
        Interarrival jitter: 400
        Last SR timestamp: 3012766466 (0xb3932b02)
        Delay since last SR timestamp: 403963 (6163 milliseconds)
Real-time Transport Control Protocol (Source description)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Source count: 1
    Packet type: Source description (202)
    Length: 19 (80 bytes)
    Chunk 1, SSRC/CSRC 0x1D1C4454
        Identifier: 0x1d1c4454 (488391764)
        SDES items
            Type: CNAME (user and domain) (1)
            Length: 18
            Text: 0.0.0@79.170.68.84
            Type: NAME (common name) (2)
            Length: 23
            Text: Cisco IOS, VoIP Gateway
            Type: TOOL (name/version of source app) (6)
            Length: 23
            Text: Cisco IOS, VoIP Gateway
            Type: END (0)
[RTCP frame length check: OK - 112 bytes]


do you something wrong on this message for example?
best regards

**Comment by rfuchs** [comment] 2015-03-23 11:55
Does it still recognize these as duplicates?

**Comment by descartin** [comment] 2015-03-23 12:05
yes, seems those ones are creating the same duplicate log

**Comment by rfuchs** [comment] 2015-03-23 12:13
Can you tell whether the "Extended highest sequence number received" changes between these packets? I would expect that it does and with it changing, these packets shouldn't count as duplicates.

**Comment by descartin** [comment] 2015-03-23 12:16
yes seems they get increased on each packet

Real-time Transport Control Protocol (Receiver Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Receiver Report (201)
    Length: 7 (32 bytes)
    Sender SSRC: 0x1d1c4454 (488391764)
    Source 1
        Identifier: 0x253c405e (624705630)
        SSRC contents
            Fraction lost: 0 / 256
            Cumulative number of packets lost: 0
        Extended highest sequence number received: 24231
            Sequence number cycles count: 0
            Highest sequence number received: 24231
        Interarrival jitter: 560
        Last SR timestamp: 3012307714 (0xb38c2b02)
        Delay since last SR timestamp: 428867 (6543 milliseconds)
Real-time Transport Control Protocol (Source description)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Source count: 1
    Packet type: Source description (202)
    Length: 19 (80 bytes)
    Chunk 1, SSRC/CSRC 0x1D1C4454
        Identifier: 0x1d1c4454 (488391764)
        SDES items
            Type: CNAME (user and domain) (1)
            Length: 18
            Text: 0.0.0@79.170.68.84
            Type: NAME (common name) (2)
            Length: 23
            Text: Cisco IOS, VoIP Gateway
            Type: TOOL (name/version of source app) (6)
            Length: 23
            Text: Cisco IOS, VoIP Gateway
            Type: END (0)
[RTCP frame length check: OK - 112 bytes]

************
Real-time Transport Control Protocol (Receiver Report)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Reception report count: 1
    Packet type: Receiver Report (201)
    Length: 7 (32 bytes)
    Sender SSRC: 0x1d1c4454 (488391764)
    Source 1
        Identifier: 0x253c405e (624705630)
        SSRC contents
            Fraction lost: 0 / 256
            Cumulative number of packets lost: 0
        Extended highest sequence number received: 24562
            Sequence number cycles count: 0
            Highest sequence number received: 24562
        Interarrival jitter: 400
        Last SR timestamp: 3012766466 (0xb3932b02)
        Delay since last SR timestamp: 403963 (6163 milliseconds)
Real-time Transport Control Protocol (Source description)
    10.. .... = Version: RFC 1889 Version (2)
    ..0. .... = Padding: False
    ...0 0001 = Source count: 1
    Packet type: Source description (202)
    Length: 19 (80 bytes)
    Chunk 1, SSRC/CSRC 0x1D1C4454
        Identifier: 0x1d1c4454 (488391764)
        SDES items
            Type: CNAME (user and domain) (1)
            Length: 18
            Text: 0.0.0@79.170.68.84
            Type: NAME (common name) (2)
            Length: 23
            Text: Cisco IOS, VoIP Gateway
            Type: TOOL (name/version of source app) (6)
            Length: 23
            Text: Cisco IOS, VoIP Gateway
            Type: END (0)
[RTCP frame length check: OK - 112 bytes]

**Comment by rfuchs** [comment] 2015-03-23 12:24
These shouldn't count as duplicates then, since the changing sequence number is within the first 24 bytes of the packet.

**Comment by tommyapeldk** [comment] 2015-04-27 14:30
Hello, FYI I had to push the RTP_LOOP_PROTECT to 28 because the significant change was in bytes 25 to 28 for RTCP packets coming from our asterisk

Last SR timestamp: 3117543107 (0xb9d1eec3)
Last SR timestamp: 3117870751 (0xb9d6ee9f)

Extended highest sequence number received: 52317 <- stays the same

**Comment by rfuchs** [comment] 2015-04-27 14:34
Interesting that the seq number stays the same. Thanks.

**Comment by descartin** [comment] 2015-04-27 16:03
Hello Richard

so in this case, in the receiver report messages i get with the "Extended highest sequence number received" changing, why could be that i see them as duplicated also. would still haev sense to increaset the rtp_loop_protect up to 28 to include the "Last SR timestamp" also changing?

thanks a lot and regards
david

**Comment by rfuchs** [comment] 2015-04-27 16:08
No you shouldn't have to. Honestly I have no idea why packets with different sequence numbers would be seen as duplicated. But increasing the value doesn't hurt either way.

**Comment by kfcviptel** [comment] 2015-05-18 07:16
We had to increase the size of the loop protection buffer to 30. We had a test setup which primarily used the echo test in Asterisk to generate load, and that apparently requires 30 bytes.

What is the memory implications of this loop protection buffer, when the number of calls grow?

**Comment by tommyapeldk** [comment] 2015-05-18 07:24
kfcviptel, you'll use ( 30 bytes * 2 ) * active calls, so for 100 calls that'll be 6000 bytes of buffer so not really much of an issue unless I'd say

**Comment by rfuchs** [comment] 2015-05-19 15:19
I'm not concerned about memory usage, but rather CPU impact on having to run the dupe check for every received packed.

**Comment by dtwright** [comment] 2016-04-04 16:22
I know it's been a little while since there's been activity on this issue, but I have been seeing this as well from time to time. As a bit of background, my node running RTPEngine is Amazon EC2 hosted with static bidirectional NAT, so rtpengine is running with `--interface=<INTERNAL_IP>!<EXTERNAL_IP>`. When I see the duplicate packet messages in the logs, they'll be accompanied with messages like this:

`Apr  4 15:45:32 ip-172-31-18-97 rtpengine[2805]: [UPGVwCe0Nw5KKOCKzegdhv1EI-rsK0SA port 43034] Confirmed peer address as <EXTERNAL_IP>:43044
Apr  4 15:45:33 ip-172-31-18-97 rtpengine[2805]: [UPGVwCe0Nw5KKOCKzegdhv1EI-rsK0SA port 43035] Confirmed peer address as <ACTUAL_REMOTE_IP>:32206
Apr  4 15:45:33 ip-172-31-18-97 rtpengine[2805]: [UPGVwCe0Nw5KKOCKzegdhv1EI-rsK0SA port 43035] Switching local interface to <INTERNAL_IP>:43035
Apr  4 15:45:33 ip-172-31-18-97 rtpengine[2805]: [UPGVwCe0Nw5KKOCKzegdhv1EI-rsK0SA port 43035] More than 30 duplicate packets detected, dropping packet to avoid potential loop
Apr  4 15:45:38 ip-172-31-18-97 rtpengine[2805]: [UPGVwCe0Nw5KKOCKzegdhv1EI-rsK0SA port 43035] More than 30 duplicate packets detected, dropping packet to avoid potential loop`

It also seems to happen most frequently when calls are in progress that set up a stream relay, but actually negotiated a direct media connection between endpoints with ICE (so no packets actually traverse rtpengine during the call). I don't think it happens on every call like this, however.

I don't have a packet log yet because I'm working on reproducing/triggering it myself – I see it sporadically with real calls, and am working on a repo scenario so I can trigger it consistently and get some packet logs. If/when I get that I'll post a packet log here... In the mean time, if you have any ideas about what might be causing this or next investigation steps that might help, let me know.

**Comment by rfuchs** [comment] 2016-04-04 16:58
Can you post the full log for such a call? Preferable with log level turned to 7. Looks like rtpengine ends up talking to itself for some reason.

**Comment by AmericanModelUnitedNations** [comment] 2016-04-05 15:12
This log has several calls on the same server - one with the duplicate packet issue and a couple calls without it (separated by "------------"). The main thing I notice is that the call generating the duplicate packet messages is one sided (routing through the proxy only one direction). I have noticed in our production environment that the call setup sometimes works out this way; it still has bidirectional audio in the call but sometimes only negotiates using the proxy in one direction.
[rtpengine-log.txt](https://github.com/sipwise/rtpengine/files/204770/rtpengine-log.txt)

**Comment by dtwright** [comment] 2016-04-05 15:15
This log has several calls on the same server - one with the duplicate packet issue and a couple calls without it (separated by "------------"). The main thing I notice is that the call generating the duplicate packet messages is one sided (routing through the proxy only one direction). I have noticed in our production environment that the call setup sometimes works out this way; it still has bidirectional audio in the call but sometimes only negotiates using the proxy in one direction.
[rtpengine-log.txt](https://github.com/sipwise/rtpengine/files/204772/rtpengine-log.txt)

**Comment by rfuchs** [comment] 2016-04-05 15:31
I see that you're using force-relay and that these streams are put into passthrough mode. Perhaps it's STUN connectivity checks or something like that which trigger this message. A packet dump would be helpful to confirm this.

If you're certain that you're not creating a forwarding loop anywhere (and this log doesn't look like a loop), then you can just disable the dup check when compiling rtpengine. However you've mentioned that sometimes log lines appear confirming the peer address as its own address. That would indeed indicate a loop, but I don't see this in this particular log.

**Comment by dtwright** [comment] 2016-04-05 15:41
Thanks – that all makes sense. This particular log is from our dev system (which is configured identically to production but has a much lower traffic volume). I'll try to get a packet logs and rtpengine logs of a couple calls that match these scenarios over the next couple days on our production server and post them. I suspect there may be two different things happening that are both generating the dup message – your note about the STUN check is interesting, because sometimes the dup message doesn't generate any other infrastructure alarms or noticeable traffic (which I suspect would be the case for STUN messages), but sometimes they correlate to a network traffic spike that's logged by the AWS monitoring system and triggers a traffic alarm in our monitoring system.

**Comment by dtwright** [comment] 2016-04-08 19:05
I've attached an rtpengine log (level=7) for three calls that exhibit this problem. It looks like my previous assertion about these happening in single-ended relay sessions was mistaken – at least one of them is double-ended (the relay detected speex/16000 as the codec both ways). 

I also have packet logs covering the relevant times (about 75MB worth). I've looked at them and do see lots of STUN messages, but can't tell if that's related. Our clients are using SRTP so the voice packets don't seem to contain anything helpful. You can find the packet captures in Google Drive at https://drive.google.com/folderview?id=0B_WSo6zgZnfRWldMUC12dGREQmc&usp=sharing. 
[sip-duplicate-log.txt](https://github.com/sipwise/rtpengine/files/210715/sip-duplicate-log.txt)

**Comment by rfuchs** [comment] 2016-04-11 17:20
OK, so looking at call-id "bseCnpJ6K0i5gKx-xTL0yO4kjlFjB6.r" here. Tag "91yb6dyTkvSVYXtYRCO-uDt44.RdPDfk" is side A, tag "Jx.LgtHn8SHQp801OOEdggaOHzwI4cO5" is side B.

Side A sends the original offer, advertising 166.176.184.152:7027 as its address. Rtpengine inserts itself as candidate at 54.165.68.45:40888 and the offer is sent to B.

Side B sends an answer, advertising 70.20.28.85:34630 as its endpoint. Rtpengine inserts itself as candidate with 54.165.68.45:40908 and the answer is relayed back to A.

Side then sends a reinvite, now advertising 54.165.68.45:40888 as its endpoint. Wait, what? That's rtpengine's local port! Side B then does the same thing. As a result, rtpengine ends up sending packets to itself.

I believe that this is actually expected when using force-relay, as ICE requires an updated offer to be sent after endpoints have been negotiated, and since force-relay leaves the main endpoint addresses unchanged and passes through STUN packet, you end up with a loop.

What rtpengine should do instead is pay special attention to this case and detect when its own addresses are used as SDP peer addresses. Will fix.

**Comment by dtwright** [comment] 2016-04-11 17:40
Got it! Thanks. When your fix is in, I can install and test it in our staging environment.

**Comment by rfuchs** [comment] 2016-04-12 14:51
Have a look at the commit referenced just above. I believe it should fix your issue. Let me know.

**Comment by dtwright** [comment] 2016-04-12 20:43
confirmed from log messages that it is detecting this case correctly, and the duplicate packet issue seems to be gone.

**Closed** 2016-08-11 16:39 UTC

**Comment by rfuchs** [comment] 2017-02-28 16:27
The corresponding commit is 94e3c8f9
