### ISSUE TITLE
Unable to build via dpkg-buildpackage on Debian Stretch with gnutls

### ISSUE THREAD

**Issue by covalschi** [sipwise/rtpengine#685] opened 2019-01-23 11:31 UTC
Unable to pass auto-daemon-tests.pl if gnutls crypto is chosen over openssl library.  Building without g729, everything else is by default.
Here's the log where it stops - and daemon is immediately defunct in process list, can't even strace it. 
If I install remove gnutls and install openssl library it's all fine.
```LD_PRELOAD=../t/tests-preload.so RTPE_BIN=../daemon/rtpengine TEST_SOCKET_PATH=./fake-sockets \
perl -I../perl auto-daemon-tests.pl
ok 1 - LD_PRELOAD present
ok 2 - preload library is active
ok 3 - RTPE_BIN points to executable
ok 4 - daemon launched in background
No such file or directory  ...propagated at auto-daemon-tests.pl line 31.
Died at auto-daemon-tests.pl line 481.
END failed--call queue aborted.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 22 just after 4.
Makefile:90: recipe for target 'daemon-tests' failed
make[3]: *** [daemon-tests] Error 22```

**Comment by rfuchs** [comment] 2019-01-23 14:26
No I'm asking about the daemon itself, outside of the test suite.

So far I haven't been able to reproduce this. Building with libcurl4-gnutls-dev and libgnutls-openssl27 installed. What else do you have installed that would prefer gnutls over openssl? Do you have any build logs? Output of `dpkg -l` ?

**Comment by rfuchs** [comment] 2019-01-23 14:35
In that case I'll have to close this since it's not reproducible and no further information is available.

**Closed by rfuchs** 2019-01-23 14:35 UTC
