### ISSUE TITLE
disable injection of dtmf tones

### ISSUE THREAD

**Issue by sashasaturn** [sipwise/rtpengine#861] opened 2019-10-15 15:02 UTC
Hi all,

Could you please help me to permanently disable 'Injection of DTMF events or PCM DTMF tones into running audio streams' when building the projects.

Thanks,

Alex

**Comment by rfuchs** [comment] 2019-10-16 14:45
Why?

**Comment by sashasaturn** [comment] 2019-10-16 15:37
@rfuchs  thanks for checking
The reason why I would like to disable the injection of DTMF events - chopping and jamming recordings right after DTMF tones injection and to the end of recording file. In all other cases it recording works just fine. 
As soon as I test that without DTMF injections all works as expected I will collect all necessary debug information and report about it properly
One of the ways to remove DTMF event, If I understand correctly, is to exclude telephone-event codec, right?
Thanks

**Comment by rfuchs** [comment] 2019-10-16 15:42
Ah you mean DTMF events are injected into audio files generated from the recording daemon?

**Comment by sashasaturn** [comment] 2019-10-16 15:46
yes, sorry for not being clear on explanations

**Comment by sashasaturn** [comment] 2019-10-21 14:43
@rfuchs sorry to bother you. Any suggestion?

**Comment by rfuchs** [comment] 2019-10-21 14:45
I consider this a bug. It will be fixed.

**Comment by sashasaturn** [comment] 2019-10-30 10:20
Hi @rfuchs, here is some additional info about the issue.

Looks like the issue appears only in conference calls or voicemail service where you have to enter a room number via DTMF

After processing and mixing RTP stream into mp3 or wav with rtpengine-recording daemon
[syslog.zip](https://github.com/sipwise/rtpengine/files/3788220/syslog.zip)
[SW093533931291019-1230853364%40100.126.5.60-f48b8b49d2d23fe9-mix.mp3-mod.pcapng.zip](https://github.com/sipwise/rtpengine/files/3788222/SW093533931291019-1230853364.40100.126.5.60-f48b8b49d2d23fe9-mix.mp3-mod.pcapng.zip)
[SW093533931291019-1230853364%40100.126.5.60-f48b8b49d2d23fe9-mix.mp3.zip](https://github.com/sipwise/rtpengine/files/3788223/SW093533931291019-1230853364.40100.126.5.60-f48b8b49d2d23fe9-mix.mp3.zip)

, some of the calls audio is distorted. Without rtpengine-recording proc and /etc/rtpengine/rtpengine.conf  recording-method=pcap produce clean audio.   Below our full desired configurations attached mixed file and corresponding pcap and logs for a distorted call scenario. 
Here are my current configs:

/etc/rtpengine/rtpengine.conf 
[rtpengine]
interface=100.126.102.3
foreground=true
table=0
num-threads=16
listen-ng=22222
port-min=30000
port-max=40000
recording-dir=/var/spool/rtpengine
recording-method=proc
#recording-method=pcap
recording-format=raw
log-stderr=false
log-facility=local1
log-facility-rtcp=local1
log-facility-cdr=local1
log-level=7
delete-delay=0
iptables-chain=rtpengine
#pidfile = /var/run/rtpengine.pid
silent-timeout=3600
 
 
/etc/rtpengine/rtpengine-recording.conf 
[rtpengine-recording]
table = 0
output-format = mp3
output-storage = file
resample-to = 16000
mp3-bitrate = 24000
output-mixed = true
log-level = 7
spool-dir = /var/spool/rtpengine
output-dir = /opt/recording

**Comment by sashasaturn** [comment] 2019-10-31 18:10
@rfuchs sorry for bothering you, but I have some additional info ... 
When I change output-mixed to false in rtpengine-recording section individual mp3 files looks completely OK, meanwhile -mix.mp3 file still distorted.

**Comment by rfuchs** [comment] 2019-11-01 16:13
Looks like this has nothing to do with DTMF, but rather is caused by a bug in the mixer code which gets confused by a pause (and subsequent timestamp gap) in one of the RTP streams.

**Comment by rfuchs** [comment] 2019-11-01 16:51
Please try with the commit referenced above

**Comment by john08burke** [comment] 2019-11-04 15:57
I was having the same issue with distorted mixed files. I tested the referenced commit and can confirm the distortions have been fixed. However, the mixed recordings are about a second out of sync and sound like the two parties are talking over each other. I have shared privately the mixed file and associated pcap file.

**Comment by rfuchs** [comment] 2019-11-04 18:19
So this sort of seems to be the opposite issue, where a TS gap is converted to a 1-second delay to compensate for it, which in this case isn't the right thing to do. Try with the additional commit above.

**Comment by john08burke** [comment] 2019-11-04 20:46
I applied the second commit and don't see the TS issues anymore. The audio on those files is now a bit choppy though. I sent an example that had a 5s TS filled correctly, but has choppy audio for the remainder of the call.

**Comment by rfuchs** [comment] 2019-11-05 14:41
Ok I see what you mean in the mp3 you sent me, but I don't see the same thing when I replay the pcap on my test machine. Could it just be a resource overload on your recording system?

**Comment by john08burke** [comment] 2019-11-05 17:13
I don't think it's a resource limitation. The examples that I sent were taken when there was only a couple calls up. The choppiness only seems to come into play when there is a TS gap. Clients that send continuous RTP don't seem to have issues.

To summarize:
- mixing to wav or mp3 produce choppiness when TS gap is present
- single files are clear, but the TS gap is not filled correctly and make it impossible to do any post-processing

System:
- debian 9.11
- Version: 7.1.0.0+0~mr7.1.0.0 git-master-2046373

rtpengine.conf
```
[rtpengine]
table = 0
no-fallback = true

interface = internal/__IP_ADDRESS__
listen-ng = __IP_ADDRESS__:22222
listen-cli = 9900

timeout = 60
silent-timeout = 28800
final-timeout = 0
offer-timeout = 3600
delete-delay = 0
tos = 184

foreground = false
pidfile = /var/run/ngcp-rtpengine-daemon.pid
num-threads = 8

recording-dir = /var/spool/rtpengine
recording-method = proc
```

rtpengine-recording.conf
```
[rtpengine-recording]
table = 0
num-threads = 8
spool-dir = /var/spool/rtpengine

pidfile = /run/ngcp-rtpengine-recording-daemon.pid

output-dir = /recordings
output-storage = file
output-format = wav
output-mixed = 1
output-single = 1
resample-to = 16000

mysql-host = localhost
mysql-port = 3306
mysql-user = __USERNAME__
mysql-pass = __PASSWORD__
mysql-db = rtpengine
```

**Comment by rfuchs** [comment] 2019-11-05 18:27
Tried it again on a stretch machine with the exact same config and still cannot reproduce.

**Comment by john08burke** [comment] 2019-11-05 18:47
Hmm... how can I perform a similar test on my system? Are you able to playback the pcap directly into the recording-daemon?

**Comment by rfuchs** [comment] 2019-11-06 14:05
Yes, there is a script included: https://github.com/sipwise/rtpengine/blob/master/utils/kernel-intercept-pcap-replay.pl

It takes control of the capture interface so it only works with the main rtpengine daemon stopped (or against a separate instance of the recording daemon using a different kernel table).

**Comment by john08burke** [comment] 2019-11-06 18:18
The script is failing when it tries to open an fd for /proc/rtpengine/0/control.
`No such file or directory at ./kernel-intercept-pcap-replay.pl line 16.`

I have the main daemon stopped and the kernel module is loaded.

ls -l /proc/rtpengine/
```
total 0
--w--w---- 1 root root 0 Nov  6 18:03 control
-r--r--r-- 1 root root 0 Nov  6 18:03 list
```

lsmod | grep RTP
```
xt_RTPENGINE           45056  0
x_tables               36864  2 ip_tables,xt_RTPENGINE
```

recording-daemon command:
```
rtpengine-recording -t 0 -f -L 7 -E --spool-dir=/var/spool/rtpengine --output-dir=/recordings --output-format=mp3 --output-mixed=1
```
Any suggestions?

**Comment by rfuchs** [comment] 2019-11-06 18:32
`echo add 0 > /proc/rtpengine/control`

**Comment by john08burke** [comment] 2019-11-06 22:03
Thanks. I was also unable to reproduce the choppiness in any of my test cases. It would seem isolated to traffic traversing the main daemon.

I was able to reproduce the TS gap not being filled correctly in the single file. The top two tracks are the single files output from the daemon. The bottom track is the mixed output. Highlighted shows the TS gap, which is correctly compensated for in mixed but not in the middle single.
![image](https://user-images.githubusercontent.com/36895232/68341012-24810980-00ad-11ea-82e4-53f97ed9db7d.png)

**Comment by rfuchs** [comment] 2019-11-11 13:19
Yeah individual outputs don't compensate for timestamp gaps. They just skip over it.

**Closed** 2019-11-11 13:36 UTC
